// Code generated by "so bind"; DO NOT EDIT.
// sobind: 1 skipped

package libsqlite3

import "solod.dev/so/c"
var _ c.Char

type Callback func(any, c.Int, **c.Char, **c.Char) c.Int

type Syscall_ptr func()

type Destructor_type func(any)

type Fts5_extension_function func(*ConstFts5ExtensionApi, *Fts5Context, *Context, c.Int, **Value)

//so:extern sqlite3
type Sqlite3 struct {}

//so:extern sqlite3_file
type File struct {
	PMethods *Io_methods `c:"pMethods"`
}

//so:extern struct sqlite3_io_methods
type Io_methods struct {
	IVersion c.Int `c:"iVersion"`
	XClose func(*File) c.Int `c:"xClose"`
	XRead func(*File, any, c.Int, c.LongLong) c.Int `c:"xRead"`
	XWrite func(*File, *c.ConstVoid, c.Int, c.LongLong) c.Int `c:"xWrite"`
	XTruncate func(*File, c.LongLong) c.Int `c:"xTruncate"`
	XSync func(*File, c.Int) c.Int `c:"xSync"`
	XFileSize func(*File, *c.LongLong) c.Int `c:"xFileSize"`
	XLock func(*File, c.Int) c.Int `c:"xLock"`
	XUnlock func(*File, c.Int) c.Int `c:"xUnlock"`
	XCheckReservedLock func(*File, *c.Int) c.Int `c:"xCheckReservedLock"`
	XFileControl func(*File, c.Int, any) c.Int `c:"xFileControl"`
	XSectorSize func(*File) c.Int `c:"xSectorSize"`
	XDeviceCharacteristics func(*File) c.Int `c:"xDeviceCharacteristics"`
	XShmMap func(*File, c.Int, c.Int, c.Int, *any) c.Int `c:"xShmMap"`
	XShmLock func(*File, c.Int, c.Int, c.Int) c.Int `c:"xShmLock"`
	XShmBarrier func(*File) `c:"xShmBarrier"`
	XShmUnmap func(*File, c.Int) c.Int `c:"xShmUnmap"`
	XFetch func(*File, c.LongLong, c.Int, *any) c.Int `c:"xFetch"`
	XUnfetch func(*File, c.LongLong, any) c.Int `c:"xUnfetch"`
}

//so:extern sqlite3_mutex
type Mutex struct {}

//so:extern sqlite3_api_routines
type Api_routines struct {}

//so:extern sqlite3_vfs
type Vfs struct {
	IVersion c.Int `c:"iVersion"`
	SzOsFile c.Int `c:"szOsFile"`
	MxPathname c.Int `c:"mxPathname"`
	PNext *Vfs `c:"pNext"`
	ZName *c.Char `c:"zName"`
	PAppData any `c:"pAppData"`
	XOpen func(*Vfs, *c.ConstChar, *File, c.Int, *c.Int) c.Int `c:"xOpen"`
	XDelete func(*Vfs, *c.ConstChar, c.Int) c.Int `c:"xDelete"`
	XAccess func(*Vfs, *c.ConstChar, c.Int, *c.Int) c.Int `c:"xAccess"`
	XFullPathname func(*Vfs, *c.ConstChar, c.Int, *c.Char) c.Int `c:"xFullPathname"`
	XDlOpen func(*Vfs, *c.ConstChar) any `c:"xDlOpen"`
	XDlError func(*Vfs, c.Int, *c.Char) `c:"xDlError"`
	XDlSym func(*Vfs, any, *c.ConstChar) func() `c:"xDlSym"`
	XDlClose func(*Vfs, any) `c:"xDlClose"`
	XRandomness func(*Vfs, c.Int, *c.Char) c.Int `c:"xRandomness"`
	XSleep func(*Vfs, c.Int) c.Int `c:"xSleep"`
	XCurrentTime func(*Vfs, *float64) c.Int `c:"xCurrentTime"`
	XGetLastError func(*Vfs, c.Int, *c.Char) c.Int `c:"xGetLastError"`
	XCurrentTimeInt64 func(*Vfs, *c.LongLong) c.Int `c:"xCurrentTimeInt64"`
	XSetSystemCall func(*Vfs, *c.ConstChar, func()) c.Int `c:"xSetSystemCall"`
	XGetSystemCall func(*Vfs, *c.ConstChar) func() `c:"xGetSystemCall"`
	XNextSystemCall func(*Vfs, *c.ConstChar) *c.Char `c:"xNextSystemCall"`
}

//so:extern sqlite3_mem_methods
type Mem_methods struct {
	XMalloc func(c.Int) any `c:"xMalloc"`
	XFree func(any) `c:"xFree"`
	XRealloc func(any, c.Int) any `c:"xRealloc"`
	XSize func(any) c.Int `c:"xSize"`
	XRoundup func(c.Int) c.Int `c:"xRoundup"`
	XInit func(any) c.Int `c:"xInit"`
	XShutdown func(any) `c:"xShutdown"`
	PAppData any `c:"pAppData"`
}

//so:extern sqlite3_stmt
type Stmt struct {}

//so:extern sqlite3_value
type Value struct {}

//so:extern sqlite3_context
type Context struct {}

//so:extern sqlite3_vtab
type Vtab struct {
	PModule *Module `c:"pModule"`
	NRef c.Int `c:"nRef"`
	ZErrMsg *c.Char `c:"zErrMsg"`
}

//so:extern sqlite3_module
type Module struct {
	IVersion c.Int `c:"iVersion"`
	XCreate func(*Sqlite3, any, c.Int, **c.ConstChar, **Vtab, **c.Char) c.Int `c:"xCreate"`
	XConnect func(*Sqlite3, any, c.Int, **c.ConstChar, **Vtab, **c.Char) c.Int `c:"xConnect"`
	XBestIndex func(*Vtab, *Index_info) c.Int `c:"xBestIndex"`
	XDisconnect func(*Vtab) c.Int `c:"xDisconnect"`
	XDestroy func(*Vtab) c.Int `c:"xDestroy"`
	XOpen func(*Vtab, **Vtab_cursor) c.Int `c:"xOpen"`
	XClose func(*Vtab_cursor) c.Int `c:"xClose"`
	XFilter func(*Vtab_cursor, c.Int, *c.ConstChar, c.Int, **Value) c.Int `c:"xFilter"`
	XNext func(*Vtab_cursor) c.Int `c:"xNext"`
	XEof func(*Vtab_cursor) c.Int `c:"xEof"`
	XColumn func(*Vtab_cursor, *Context, c.Int) c.Int `c:"xColumn"`
	XRowid func(*Vtab_cursor, *c.LongLong) c.Int `c:"xRowid"`
	XUpdate func(*Vtab, c.Int, **Value, *c.LongLong) c.Int `c:"xUpdate"`
	XBegin func(*Vtab) c.Int `c:"xBegin"`
	XSync func(*Vtab) c.Int `c:"xSync"`
	XCommit func(*Vtab) c.Int `c:"xCommit"`
	XRollback func(*Vtab) c.Int `c:"xRollback"`
	XFindFunction func(*Vtab, c.Int, *c.ConstChar, *func(*Context, c.Int, **Value), *any) c.Int `c:"xFindFunction"`
	XRename func(*Vtab, *c.ConstChar) c.Int `c:"xRename"`
	XSavepoint func(*Vtab, c.Int) c.Int `c:"xSavepoint"`
	XRelease func(*Vtab, c.Int) c.Int `c:"xRelease"`
	XRollbackTo func(*Vtab, c.Int) c.Int `c:"xRollbackTo"`
	XShadowName func(*c.ConstChar) c.Int `c:"xShadowName"`
	XIntegrity func(*Vtab, *c.ConstChar, *c.ConstChar, c.Int, **c.Char) c.Int `c:"xIntegrity"`
}

//so:extern sqlite3_index_info
type Index_info struct {
	NConstraint c.Int `c:"nConstraint"`
	AConstraint *Index_constraint `c:"aConstraint"`
	NOrderBy c.Int `c:"nOrderBy"`
	AOrderBy *Index_orderby `c:"aOrderBy"`
	AConstraintUsage *Index_constraint_usage `c:"aConstraintUsage"`
	IdxNum c.Int `c:"idxNum"`
	IdxStr *c.Char `c:"idxStr"`
	NeedToFreeIdxStr c.Int `c:"needToFreeIdxStr"`
	OrderByConsumed c.Int `c:"orderByConsumed"`
	EstimatedCost float64 `c:"estimatedCost"`
	EstimatedRows c.LongLong `c:"estimatedRows"`
	IdxFlags c.Int `c:"idxFlags"`
	ColUsed c.ULongLong `c:"colUsed"`
}

//so:extern struct sqlite3_index_constraint
type Index_constraint struct {
	IColumn c.Int `c:"iColumn"`
	Op c.UChar `c:"op"`
	Usable c.UChar `c:"usable"`
	ITermOffset c.Int `c:"iTermOffset"`
}

//so:extern struct sqlite3_index_orderby
type Index_orderby struct {
	IColumn c.Int `c:"iColumn"`
	Desc c.UChar `c:"desc"`
}

//so:extern struct sqlite3_index_constraint_usage
type Index_constraint_usage struct {
	ArgvIndex c.Int `c:"argvIndex"`
	Omit c.UChar `c:"omit"`
}

//so:extern sqlite3_vtab_cursor
type Vtab_cursor struct {
	PVtab *Vtab `c:"pVtab"`
}

//so:extern sqlite3_blob
type Blob struct {}

//so:extern sqlite3_mutex_methods
type Mutex_methods struct {
	XMutexInit func() c.Int `c:"xMutexInit"`
	XMutexEnd func() c.Int `c:"xMutexEnd"`
	XMutexAlloc func(c.Int) *Mutex `c:"xMutexAlloc"`
	XMutexFree func(*Mutex) `c:"xMutexFree"`
	XMutexEnter func(*Mutex) `c:"xMutexEnter"`
	XMutexTry func(*Mutex) c.Int `c:"xMutexTry"`
	XMutexLeave func(*Mutex) `c:"xMutexLeave"`
	XMutexHeld func(*Mutex) c.Int `c:"xMutexHeld"`
	XMutexNotheld func(*Mutex) c.Int `c:"xMutexNotheld"`
}

//so:extern sqlite3_str
type Str struct {}

//so:extern sqlite3_pcache
type Pcache struct {}

//so:extern sqlite3_pcache_page
type Pcache_page struct {
	PBuf any `c:"pBuf"`
	PExtra any `c:"pExtra"`
}

//so:extern sqlite3_pcache_methods2
type Pcache_methods2 struct {
	IVersion c.Int `c:"iVersion"`
	PArg any `c:"pArg"`
	XInit func(any) c.Int `c:"xInit"`
	XShutdown func(any) `c:"xShutdown"`
	XCreate func(c.Int, c.Int, c.Int) *Pcache `c:"xCreate"`
	XCachesize func(*Pcache, c.Int) `c:"xCachesize"`
	XPagecount func(*Pcache) c.Int `c:"xPagecount"`
	XFetch func(*Pcache, c.UInt, c.Int) *Pcache_page `c:"xFetch"`
	XUnpin func(*Pcache, *Pcache_page, c.Int) `c:"xUnpin"`
	XRekey func(*Pcache, *Pcache_page, c.UInt, c.UInt) `c:"xRekey"`
	XTruncate func(*Pcache, c.UInt) `c:"xTruncate"`
	XDestroy func(*Pcache) `c:"xDestroy"`
	XShrink func(*Pcache) `c:"xShrink"`
}

//so:extern sqlite3_pcache_methods
type Pcache_methods struct {
	PArg any `c:"pArg"`
	XInit func(any) c.Int `c:"xInit"`
	XShutdown func(any) `c:"xShutdown"`
	XCreate func(c.Int, c.Int) *Pcache `c:"xCreate"`
	XCachesize func(*Pcache, c.Int) `c:"xCachesize"`
	XPagecount func(*Pcache) c.Int `c:"xPagecount"`
	XFetch func(*Pcache, c.UInt, c.Int) any `c:"xFetch"`
	XUnpin func(*Pcache, any, c.Int) `c:"xUnpin"`
	XRekey func(*Pcache, any, c.UInt, c.UInt) `c:"xRekey"`
	XTruncate func(*Pcache, c.UInt) `c:"xTruncate"`
	XDestroy func(*Pcache) `c:"xDestroy"`
}

//so:extern sqlite3_backup
type Backup struct {}

//so:extern sqlite3_snapshot
type Snapshot struct {
	Hidden [48]c.UChar `c:"hidden"`
}

//so:extern sqlite3_rtree_geometry
type Rtree_geometry struct {
	PContext any `c:"pContext"`
	NParam c.Int `c:"nParam"`
	AParam *float64 `c:"aParam"`
	PUser any `c:"pUser"`
	XDelUser func(any) `c:"xDelUser"`
}

//so:extern sqlite3_rtree_query_info
type Rtree_query_info struct {
	PContext any `c:"pContext"`
	NParam c.Int `c:"nParam"`
	AParam *float64 `c:"aParam"`
	PUser any `c:"pUser"`
	XDelUser func(any) `c:"xDelUser"`
	ACoord *float64 `c:"aCoord"`
	AnQueue *c.UInt `c:"anQueue"`
	NCoord c.Int `c:"nCoord"`
	ILevel c.Int `c:"iLevel"`
	MxLevel c.Int `c:"mxLevel"`
	IRowid c.LongLong `c:"iRowid"`
	RParentScore float64 `c:"rParentScore"`
	EParentWithin c.Int `c:"eParentWithin"`
	EWithin c.Int `c:"eWithin"`
	RScore float64 `c:"rScore"`
	ApSqlParam **Value `c:"apSqlParam"`
}

//so:extern Fts5ExtensionApi
type Fts5ExtensionApi struct {
	IVersion c.Int `c:"iVersion"`
	XUserData func(*Fts5Context) any `c:"xUserData"`
	XColumnCount func(*Fts5Context) c.Int `c:"xColumnCount"`
	XRowCount func(*Fts5Context, *c.LongLong) c.Int `c:"xRowCount"`
	XColumnTotalSize func(*Fts5Context, c.Int, *c.LongLong) c.Int `c:"xColumnTotalSize"`
	XTokenize func(*Fts5Context, *c.ConstChar, c.Int, any, func(any, c.Int, *c.ConstChar, c.Int, c.Int, c.Int) c.Int) c.Int `c:"xTokenize"`
	XPhraseCount func(*Fts5Context) c.Int `c:"xPhraseCount"`
	XPhraseSize func(*Fts5Context, c.Int) c.Int `c:"xPhraseSize"`
	XInstCount func(*Fts5Context, *c.Int) c.Int `c:"xInstCount"`
	XInst func(*Fts5Context, c.Int, *c.Int, *c.Int, *c.Int) c.Int `c:"xInst"`
	XRowid func(*Fts5Context) c.LongLong `c:"xRowid"`
	XColumnText func(*Fts5Context, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xColumnText"`
	XColumnSize func(*Fts5Context, c.Int, *c.Int) c.Int `c:"xColumnSize"`
	XQueryPhrase func(*Fts5Context, c.Int, any, func(*ConstFts5ExtensionApi, *Fts5Context, any) c.Int) c.Int `c:"xQueryPhrase"`
	XSetAuxdata func(*Fts5Context, any, func(any)) c.Int `c:"xSetAuxdata"`
	XGetAuxdata func(*Fts5Context, c.Int) any `c:"xGetAuxdata"`
	XPhraseFirst func(*Fts5Context, c.Int, *Fts5PhraseIter, *c.Int, *c.Int) c.Int `c:"xPhraseFirst"`
	XPhraseNext func(*Fts5Context, *Fts5PhraseIter, *c.Int, *c.Int) `c:"xPhraseNext"`
	XPhraseFirstColumn func(*Fts5Context, c.Int, *Fts5PhraseIter, *c.Int) c.Int `c:"xPhraseFirstColumn"`
	XPhraseNextColumn func(*Fts5Context, *Fts5PhraseIter, *c.Int) `c:"xPhraseNextColumn"`
	XQueryToken func(*Fts5Context, c.Int, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xQueryToken"`
	XInstToken func(*Fts5Context, c.Int, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xInstToken"`
	XColumnLocale func(*Fts5Context, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xColumnLocale"`
	XTokenize_v2 func(*Fts5Context, *c.ConstChar, c.Int, *c.ConstChar, c.Int, any, func(any, c.Int, *c.ConstChar, c.Int, c.Int, c.Int) c.Int) c.Int `c:"xTokenize_v2"`
}

//so:extern Fts5Context
type Fts5Context struct {}

//so:extern const Fts5ExtensionApi
type ConstFts5ExtensionApi struct {
	IVersion c.Int `c:"iVersion"`
	XUserData func(*Fts5Context) any `c:"xUserData"`
	XColumnCount func(*Fts5Context) c.Int `c:"xColumnCount"`
	XRowCount func(*Fts5Context, *c.LongLong) c.Int `c:"xRowCount"`
	XColumnTotalSize func(*Fts5Context, c.Int, *c.LongLong) c.Int `c:"xColumnTotalSize"`
	XTokenize func(*Fts5Context, *c.ConstChar, c.Int, any, func(any, c.Int, *c.ConstChar, c.Int, c.Int, c.Int) c.Int) c.Int `c:"xTokenize"`
	XPhraseCount func(*Fts5Context) c.Int `c:"xPhraseCount"`
	XPhraseSize func(*Fts5Context, c.Int) c.Int `c:"xPhraseSize"`
	XInstCount func(*Fts5Context, *c.Int) c.Int `c:"xInstCount"`
	XInst func(*Fts5Context, c.Int, *c.Int, *c.Int, *c.Int) c.Int `c:"xInst"`
	XRowid func(*Fts5Context) c.LongLong `c:"xRowid"`
	XColumnText func(*Fts5Context, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xColumnText"`
	XColumnSize func(*Fts5Context, c.Int, *c.Int) c.Int `c:"xColumnSize"`
	XQueryPhrase func(*Fts5Context, c.Int, any, func(*ConstFts5ExtensionApi, *Fts5Context, any) c.Int) c.Int `c:"xQueryPhrase"`
	XSetAuxdata func(*Fts5Context, any, func(any)) c.Int `c:"xSetAuxdata"`
	XGetAuxdata func(*Fts5Context, c.Int) any `c:"xGetAuxdata"`
	XPhraseFirst func(*Fts5Context, c.Int, *Fts5PhraseIter, *c.Int, *c.Int) c.Int `c:"xPhraseFirst"`
	XPhraseNext func(*Fts5Context, *Fts5PhraseIter, *c.Int, *c.Int) `c:"xPhraseNext"`
	XPhraseFirstColumn func(*Fts5Context, c.Int, *Fts5PhraseIter, *c.Int) c.Int `c:"xPhraseFirstColumn"`
	XPhraseNextColumn func(*Fts5Context, *Fts5PhraseIter, *c.Int) `c:"xPhraseNextColumn"`
	XQueryToken func(*Fts5Context, c.Int, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xQueryToken"`
	XInstToken func(*Fts5Context, c.Int, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xInstToken"`
	XColumnLocale func(*Fts5Context, c.Int, **c.ConstChar, *c.Int) c.Int `c:"xColumnLocale"`
	XTokenize_v2 func(*Fts5Context, *c.ConstChar, c.Int, *c.ConstChar, c.Int, any, func(any, c.Int, *c.ConstChar, c.Int, c.Int, c.Int) c.Int) c.Int `c:"xTokenize_v2"`
}

//so:extern Fts5PhraseIter
type Fts5PhraseIter struct {
	A *c.UChar `c:"a"`
	B *c.UChar `c:"b"`
}

//so:extern Fts5Tokenizer
type Fts5Tokenizer struct {}

//so:extern fts5_tokenizer_v2
type Fts5_tokenizer_v2 struct {
	IVersion c.Int `c:"iVersion"`
	XCreate func(any, **c.ConstChar, c.Int, **Fts5Tokenizer) c.Int `c:"xCreate"`
	XDelete func(*Fts5Tokenizer) `c:"xDelete"`
	XTokenize func(*Fts5Tokenizer, any, c.Int, *c.ConstChar, c.Int, *c.ConstChar, c.Int, func(any, c.Int, *c.ConstChar, c.Int, c.Int, c.Int) c.Int) c.Int `c:"xTokenize"`
}

//so:extern fts5_tokenizer
type Fts5_tokenizer struct {
	XCreate func(any, **c.ConstChar, c.Int, **Fts5Tokenizer) c.Int `c:"xCreate"`
	XDelete func(*Fts5Tokenizer) `c:"xDelete"`
	XTokenize func(*Fts5Tokenizer, any, c.Int, *c.ConstChar, c.Int, func(any, c.Int, *c.ConstChar, c.Int, c.Int, c.Int) c.Int) c.Int `c:"xTokenize"`
}

//so:extern fts5_api
type Fts5_api struct {
	IVersion c.Int `c:"iVersion"`
	XCreateTokenizer func(*Fts5_api, *c.ConstChar, any, *Fts5_tokenizer, func(any)) c.Int `c:"xCreateTokenizer"`
	XFindTokenizer func(*Fts5_api, *c.ConstChar, *any, *Fts5_tokenizer) c.Int `c:"xFindTokenizer"`
	XCreateFunction func(*Fts5_api, *c.ConstChar, any, func(*ConstFts5ExtensionApi, *Fts5Context, *Context, c.Int, **Value), func(any)) c.Int `c:"xCreateFunction"`
	XCreateTokenizer_v2 func(*Fts5_api, *c.ConstChar, any, *Fts5_tokenizer_v2, func(any)) c.Int `c:"xCreateTokenizer_v2"`
	XFindTokenizer_v2 func(*Fts5_api, *c.ConstChar, *any, **Fts5_tokenizer_v2) c.Int `c:"xFindTokenizer_v2"`
}

//so:extern CARRAY_BLOB
const CARRAY_BLOB = 4

//so:extern CARRAY_DOUBLE
const CARRAY_DOUBLE = 2

//so:extern CARRAY_INT32
const CARRAY_INT32 = 0

//so:extern CARRAY_INT64
const CARRAY_INT64 = 1

//so:extern CARRAY_TEXT
const CARRAY_TEXT = 3

//so:extern FTS5_TOKENIZE_AUX
const FTS5_TOKENIZE_AUX = 8

//so:extern FTS5_TOKENIZE_DOCUMENT
const FTS5_TOKENIZE_DOCUMENT = 4

//so:extern FTS5_TOKENIZE_PREFIX
const FTS5_TOKENIZE_PREFIX = 2

//so:extern FTS5_TOKENIZE_QUERY
const FTS5_TOKENIZE_QUERY = 1

//so:extern FTS5_TOKEN_COLOCATED
const FTS5_TOKEN_COLOCATED = 1

//so:extern FULLY_WITHIN
const FULLY_WITHIN = 2

//so:extern NOT_WITHIN
const NOT_WITHIN = 0

//so:extern PARTLY_WITHIN
const PARTLY_WITHIN = 1

//so:extern SQLITE3_TEXT
const TEXT = 3

//so:extern SQLITE_ABORT
const SQLITE_ABORT = 4

//so:extern SQLITE_ABORT_ROLLBACK
const SQLITE_ABORT_ROLLBACK = 516

//so:extern SQLITE_ACCESS_EXISTS
const SQLITE_ACCESS_EXISTS = 0

//so:extern SQLITE_ACCESS_READ
const SQLITE_ACCESS_READ = 2

//so:extern SQLITE_ACCESS_READWRITE
const SQLITE_ACCESS_READWRITE = 1

//so:extern SQLITE_ALTER_TABLE
const SQLITE_ALTER_TABLE = 26

//so:extern SQLITE_ANALYZE
const SQLITE_ANALYZE = 28

//so:extern SQLITE_ANY
const SQLITE_ANY = 5

//so:extern SQLITE_ATTACH
const SQLITE_ATTACH = 24

//so:extern SQLITE_AUTH
const SQLITE_AUTH = 23

//so:extern SQLITE_AUTH_USER
const SQLITE_AUTH_USER = 279

//so:extern SQLITE_BLOB
const SQLITE_BLOB = 4

//so:extern SQLITE_BUSY
const SQLITE_BUSY = 5

//so:extern SQLITE_BUSY_RECOVERY
const SQLITE_BUSY_RECOVERY = 261

//so:extern SQLITE_BUSY_SNAPSHOT
const SQLITE_BUSY_SNAPSHOT = 517

//so:extern SQLITE_BUSY_TIMEOUT
const SQLITE_BUSY_TIMEOUT = 773

//so:extern SQLITE_CANTOPEN
const SQLITE_CANTOPEN = 14

//so:extern SQLITE_CANTOPEN_CONVPATH
const SQLITE_CANTOPEN_CONVPATH = 1038

//so:extern SQLITE_CANTOPEN_DIRTYWAL
const SQLITE_CANTOPEN_DIRTYWAL = 1294

//so:extern SQLITE_CANTOPEN_FULLPATH
const SQLITE_CANTOPEN_FULLPATH = 782

//so:extern SQLITE_CANTOPEN_ISDIR
const SQLITE_CANTOPEN_ISDIR = 526

//so:extern SQLITE_CANTOPEN_NOTEMPDIR
const SQLITE_CANTOPEN_NOTEMPDIR = 270

//so:extern SQLITE_CANTOPEN_SYMLINK
const SQLITE_CANTOPEN_SYMLINK = 1550

//so:extern SQLITE_CARRAY_BLOB
const SQLITE_CARRAY_BLOB = 4

//so:extern SQLITE_CARRAY_DOUBLE
const SQLITE_CARRAY_DOUBLE = 2

//so:extern SQLITE_CARRAY_INT32
const SQLITE_CARRAY_INT32 = 0

//so:extern SQLITE_CARRAY_INT64
const SQLITE_CARRAY_INT64 = 1

//so:extern SQLITE_CARRAY_TEXT
const SQLITE_CARRAY_TEXT = 3

//so:extern SQLITE_CHECKPOINT_FULL
const SQLITE_CHECKPOINT_FULL = 1

//so:extern SQLITE_CHECKPOINT_NOOP
const SQLITE_CHECKPOINT_NOOP = -1

//so:extern SQLITE_CHECKPOINT_PASSIVE
const SQLITE_CHECKPOINT_PASSIVE = 0

//so:extern SQLITE_CHECKPOINT_RESTART
const SQLITE_CHECKPOINT_RESTART = 2

//so:extern SQLITE_CHECKPOINT_TRUNCATE
const SQLITE_CHECKPOINT_TRUNCATE = 3

//so:extern SQLITE_CONFIG_COVERING_INDEX_SCAN
const SQLITE_CONFIG_COVERING_INDEX_SCAN = 20

//so:extern SQLITE_CONFIG_GETMALLOC
const SQLITE_CONFIG_GETMALLOC = 5

//so:extern SQLITE_CONFIG_GETMUTEX
const SQLITE_CONFIG_GETMUTEX = 11

//so:extern SQLITE_CONFIG_GETPCACHE
const SQLITE_CONFIG_GETPCACHE = 15

//so:extern SQLITE_CONFIG_GETPCACHE2
const SQLITE_CONFIG_GETPCACHE2 = 19

//so:extern SQLITE_CONFIG_HEAP
const SQLITE_CONFIG_HEAP = 8

//so:extern SQLITE_CONFIG_LOG
const SQLITE_CONFIG_LOG = 16

//so:extern SQLITE_CONFIG_LOOKASIDE
const SQLITE_CONFIG_LOOKASIDE = 13

//so:extern SQLITE_CONFIG_MALLOC
const SQLITE_CONFIG_MALLOC = 4

//so:extern SQLITE_CONFIG_MEMDB_MAXSIZE
const SQLITE_CONFIG_MEMDB_MAXSIZE = 29

//so:extern SQLITE_CONFIG_MEMSTATUS
const SQLITE_CONFIG_MEMSTATUS = 9

//so:extern SQLITE_CONFIG_MMAP_SIZE
const SQLITE_CONFIG_MMAP_SIZE = 22

//so:extern SQLITE_CONFIG_MULTITHREAD
const SQLITE_CONFIG_MULTITHREAD = 2

//so:extern SQLITE_CONFIG_MUTEX
const SQLITE_CONFIG_MUTEX = 10

//so:extern SQLITE_CONFIG_PAGECACHE
const SQLITE_CONFIG_PAGECACHE = 7

//so:extern SQLITE_CONFIG_PCACHE
const SQLITE_CONFIG_PCACHE = 14

//so:extern SQLITE_CONFIG_PCACHE2
const SQLITE_CONFIG_PCACHE2 = 18

//so:extern SQLITE_CONFIG_PCACHE_HDRSZ
const SQLITE_CONFIG_PCACHE_HDRSZ = 24

//so:extern SQLITE_CONFIG_PMASZ
const SQLITE_CONFIG_PMASZ = 25

//so:extern SQLITE_CONFIG_ROWID_IN_VIEW
const SQLITE_CONFIG_ROWID_IN_VIEW = 30

//so:extern SQLITE_CONFIG_SCRATCH
const SQLITE_CONFIG_SCRATCH = 6

//so:extern SQLITE_CONFIG_SERIALIZED
const SQLITE_CONFIG_SERIALIZED = 3

//so:extern SQLITE_CONFIG_SINGLETHREAD
const SQLITE_CONFIG_SINGLETHREAD = 1

//so:extern SQLITE_CONFIG_SMALL_MALLOC
const SQLITE_CONFIG_SMALL_MALLOC = 27

//so:extern SQLITE_CONFIG_SORTERREF_SIZE
const SQLITE_CONFIG_SORTERREF_SIZE = 28

//so:extern SQLITE_CONFIG_SQLLOG
const SQLITE_CONFIG_SQLLOG = 21

//so:extern SQLITE_CONFIG_STMTJRNL_SPILL
const SQLITE_CONFIG_STMTJRNL_SPILL = 26

//so:extern SQLITE_CONFIG_URI
const SQLITE_CONFIG_URI = 17

//so:extern SQLITE_CONFIG_WIN32_HEAPSIZE
const SQLITE_CONFIG_WIN32_HEAPSIZE = 23

//so:extern SQLITE_CONSTRAINT
const SQLITE_CONSTRAINT = 19

//so:extern SQLITE_CONSTRAINT_CHECK
const SQLITE_CONSTRAINT_CHECK = 275

//so:extern SQLITE_CONSTRAINT_COMMITHOOK
const SQLITE_CONSTRAINT_COMMITHOOK = 531

//so:extern SQLITE_CONSTRAINT_DATATYPE
const SQLITE_CONSTRAINT_DATATYPE = 3091

//so:extern SQLITE_CONSTRAINT_FOREIGNKEY
const SQLITE_CONSTRAINT_FOREIGNKEY = 787

//so:extern SQLITE_CONSTRAINT_FUNCTION
const SQLITE_CONSTRAINT_FUNCTION = 1043

//so:extern SQLITE_CONSTRAINT_NOTNULL
const SQLITE_CONSTRAINT_NOTNULL = 1299

//so:extern SQLITE_CONSTRAINT_PINNED
const SQLITE_CONSTRAINT_PINNED = 2835

//so:extern SQLITE_CONSTRAINT_PRIMARYKEY
const SQLITE_CONSTRAINT_PRIMARYKEY = 1555

//so:extern SQLITE_CONSTRAINT_ROWID
const SQLITE_CONSTRAINT_ROWID = 2579

//so:extern SQLITE_CONSTRAINT_TRIGGER
const SQLITE_CONSTRAINT_TRIGGER = 1811

//so:extern SQLITE_CONSTRAINT_UNIQUE
const SQLITE_CONSTRAINT_UNIQUE = 2067

//so:extern SQLITE_CONSTRAINT_VTAB
const SQLITE_CONSTRAINT_VTAB = 2323

//so:extern SQLITE_COPY
const SQLITE_COPY = 0

//so:extern SQLITE_CORRUPT
const SQLITE_CORRUPT = 11

//so:extern SQLITE_CORRUPT_INDEX
const SQLITE_CORRUPT_INDEX = 779

//so:extern SQLITE_CORRUPT_SEQUENCE
const SQLITE_CORRUPT_SEQUENCE = 523

//so:extern SQLITE_CORRUPT_VTAB
const SQLITE_CORRUPT_VTAB = 267

//so:extern SQLITE_CREATE_INDEX
const SQLITE_CREATE_INDEX = 1

//so:extern SQLITE_CREATE_TABLE
const SQLITE_CREATE_TABLE = 2

//so:extern SQLITE_CREATE_TEMP_INDEX
const SQLITE_CREATE_TEMP_INDEX = 3

//so:extern SQLITE_CREATE_TEMP_TABLE
const SQLITE_CREATE_TEMP_TABLE = 4

//so:extern SQLITE_CREATE_TEMP_TRIGGER
const SQLITE_CREATE_TEMP_TRIGGER = 5

//so:extern SQLITE_CREATE_TEMP_VIEW
const SQLITE_CREATE_TEMP_VIEW = 6

//so:extern SQLITE_CREATE_TRIGGER
const SQLITE_CREATE_TRIGGER = 7

//so:extern SQLITE_CREATE_VIEW
const SQLITE_CREATE_VIEW = 8

//so:extern SQLITE_CREATE_VTABLE
const SQLITE_CREATE_VTABLE = 29

//so:extern SQLITE_DBCONFIG_DEFENSIVE
const SQLITE_DBCONFIG_DEFENSIVE = 1010

//so:extern SQLITE_DBCONFIG_DQS_DDL
const SQLITE_DBCONFIG_DQS_DDL = 1014

//so:extern SQLITE_DBCONFIG_DQS_DML
const SQLITE_DBCONFIG_DQS_DML = 1013

//so:extern SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE
const SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE = 1020

//so:extern SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE
const SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE = 1021

//so:extern SQLITE_DBCONFIG_ENABLE_COMMENTS
const SQLITE_DBCONFIG_ENABLE_COMMENTS = 1022

//so:extern SQLITE_DBCONFIG_ENABLE_FKEY
const SQLITE_DBCONFIG_ENABLE_FKEY = 1002

//so:extern SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER
const SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004

//so:extern SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION
const SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005

//so:extern SQLITE_DBCONFIG_ENABLE_QPSG
const SQLITE_DBCONFIG_ENABLE_QPSG = 1007

//so:extern SQLITE_DBCONFIG_ENABLE_TRIGGER
const SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003

//so:extern SQLITE_DBCONFIG_ENABLE_VIEW
const SQLITE_DBCONFIG_ENABLE_VIEW = 1015

//so:extern SQLITE_DBCONFIG_FP_DIGITS
const SQLITE_DBCONFIG_FP_DIGITS = 1023

//so:extern SQLITE_DBCONFIG_LEGACY_ALTER_TABLE
const SQLITE_DBCONFIG_LEGACY_ALTER_TABLE = 1012

//so:extern SQLITE_DBCONFIG_LEGACY_FILE_FORMAT
const SQLITE_DBCONFIG_LEGACY_FILE_FORMAT = 1016

//so:extern SQLITE_DBCONFIG_LOOKASIDE
const SQLITE_DBCONFIG_LOOKASIDE = 1001

//so:extern SQLITE_DBCONFIG_MAINDBNAME
const SQLITE_DBCONFIG_MAINDBNAME = 1000

//so:extern SQLITE_DBCONFIG_MAX
const SQLITE_DBCONFIG_MAX = 1023

//so:extern SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE
const SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE = 1006

//so:extern SQLITE_DBCONFIG_RESET_DATABASE
const SQLITE_DBCONFIG_RESET_DATABASE = 1009

//so:extern SQLITE_DBCONFIG_REVERSE_SCANORDER
const SQLITE_DBCONFIG_REVERSE_SCANORDER = 1019

//so:extern SQLITE_DBCONFIG_STMT_SCANSTATUS
const SQLITE_DBCONFIG_STMT_SCANSTATUS = 1018

//so:extern SQLITE_DBCONFIG_TRIGGER_EQP
const SQLITE_DBCONFIG_TRIGGER_EQP = 1008

//so:extern SQLITE_DBCONFIG_TRUSTED_SCHEMA
const SQLITE_DBCONFIG_TRUSTED_SCHEMA = 1017

//so:extern SQLITE_DBCONFIG_WRITABLE_SCHEMA
const SQLITE_DBCONFIG_WRITABLE_SCHEMA = 1011

//so:extern SQLITE_DBSTATUS_CACHE_HIT
const SQLITE_DBSTATUS_CACHE_HIT = 7

//so:extern SQLITE_DBSTATUS_CACHE_MISS
const SQLITE_DBSTATUS_CACHE_MISS = 8

//so:extern SQLITE_DBSTATUS_CACHE_SPILL
const SQLITE_DBSTATUS_CACHE_SPILL = 12

//so:extern SQLITE_DBSTATUS_CACHE_USED
const SQLITE_DBSTATUS_CACHE_USED = 1

//so:extern SQLITE_DBSTATUS_CACHE_USED_SHARED
const SQLITE_DBSTATUS_CACHE_USED_SHARED = 11

//so:extern SQLITE_DBSTATUS_CACHE_WRITE
const SQLITE_DBSTATUS_CACHE_WRITE = 9

//so:extern SQLITE_DBSTATUS_DEFERRED_FKS
const SQLITE_DBSTATUS_DEFERRED_FKS = 10

//so:extern SQLITE_DBSTATUS_LOOKASIDE_HIT
const SQLITE_DBSTATUS_LOOKASIDE_HIT = 4

//so:extern SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL
const SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL = 6

//so:extern SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE
const SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE = 5

//so:extern SQLITE_DBSTATUS_LOOKASIDE_USED
const SQLITE_DBSTATUS_LOOKASIDE_USED = 0

//so:extern SQLITE_DBSTATUS_MAX
const SQLITE_DBSTATUS_MAX = 13

//so:extern SQLITE_DBSTATUS_SCHEMA_USED
const SQLITE_DBSTATUS_SCHEMA_USED = 2

//so:extern SQLITE_DBSTATUS_STMT_USED
const SQLITE_DBSTATUS_STMT_USED = 3

//so:extern SQLITE_DBSTATUS_TEMPBUF_SPILL
const SQLITE_DBSTATUS_TEMPBUF_SPILL = 13

//so:extern SQLITE_DELETE
const SQLITE_DELETE = 9

//so:extern SQLITE_DENY
const SQLITE_DENY = 1

//so:extern SQLITE_DESERIALIZE_FREEONCLOSE
const SQLITE_DESERIALIZE_FREEONCLOSE = 1

//so:extern SQLITE_DESERIALIZE_READONLY
const SQLITE_DESERIALIZE_READONLY = 4

//so:extern SQLITE_DESERIALIZE_RESIZEABLE
const SQLITE_DESERIALIZE_RESIZEABLE = 2

//so:extern SQLITE_DETACH
const SQLITE_DETACH = 25

//so:extern SQLITE_DETERMINISTIC
const SQLITE_DETERMINISTIC = 2048

//so:extern SQLITE_DIRECTONLY
const SQLITE_DIRECTONLY = 524288

//so:extern SQLITE_DONE
const SQLITE_DONE = 101

//so:extern SQLITE_DROP_INDEX
const SQLITE_DROP_INDEX = 10

//so:extern SQLITE_DROP_TABLE
const SQLITE_DROP_TABLE = 11

//so:extern SQLITE_DROP_TEMP_INDEX
const SQLITE_DROP_TEMP_INDEX = 12

//so:extern SQLITE_DROP_TEMP_TABLE
const SQLITE_DROP_TEMP_TABLE = 13

//so:extern SQLITE_DROP_TEMP_TRIGGER
const SQLITE_DROP_TEMP_TRIGGER = 14

//so:extern SQLITE_DROP_TEMP_VIEW
const SQLITE_DROP_TEMP_VIEW = 15

//so:extern SQLITE_DROP_TRIGGER
const SQLITE_DROP_TRIGGER = 16

//so:extern SQLITE_DROP_VIEW
const SQLITE_DROP_VIEW = 17

//so:extern SQLITE_DROP_VTABLE
const SQLITE_DROP_VTABLE = 30

//so:extern SQLITE_EMPTY
const SQLITE_EMPTY = 16

//so:extern SQLITE_ERROR
const SQLITE_ERROR = 1

//so:extern SQLITE_ERROR_KEY
const SQLITE_ERROR_KEY = 1281

//so:extern SQLITE_ERROR_MISSING_COLLSEQ
const SQLITE_ERROR_MISSING_COLLSEQ = 257

//so:extern SQLITE_ERROR_RESERVESIZE
const SQLITE_ERROR_RESERVESIZE = 1025

//so:extern SQLITE_ERROR_RETRY
const SQLITE_ERROR_RETRY = 513

//so:extern SQLITE_ERROR_SNAPSHOT
const SQLITE_ERROR_SNAPSHOT = 769

//so:extern SQLITE_ERROR_UNABLE
const SQLITE_ERROR_UNABLE = 1537

//so:extern SQLITE_FAIL
const SQLITE_FAIL = 3

//so:extern SQLITE_FCNTL_BEGIN_ATOMIC_WRITE
const SQLITE_FCNTL_BEGIN_ATOMIC_WRITE = 31

//so:extern SQLITE_FCNTL_BLOCK_ON_CONNECT
const SQLITE_FCNTL_BLOCK_ON_CONNECT = 44

//so:extern SQLITE_FCNTL_BUSYHANDLER
const SQLITE_FCNTL_BUSYHANDLER = 15

//so:extern SQLITE_FCNTL_CHUNK_SIZE
const SQLITE_FCNTL_CHUNK_SIZE = 6

//so:extern SQLITE_FCNTL_CKPT_DONE
const SQLITE_FCNTL_CKPT_DONE = 37

//so:extern SQLITE_FCNTL_CKPT_START
const SQLITE_FCNTL_CKPT_START = 39

//so:extern SQLITE_FCNTL_CKSM_FILE
const SQLITE_FCNTL_CKSM_FILE = 41

//so:extern SQLITE_FCNTL_COMMIT_ATOMIC_WRITE
const SQLITE_FCNTL_COMMIT_ATOMIC_WRITE = 32

//so:extern SQLITE_FCNTL_COMMIT_PHASETWO
const SQLITE_FCNTL_COMMIT_PHASETWO = 22

//so:extern SQLITE_FCNTL_DATA_VERSION
const SQLITE_FCNTL_DATA_VERSION = 35

//so:extern SQLITE_FCNTL_EXTERNAL_READER
const SQLITE_FCNTL_EXTERNAL_READER = 40

//so:extern SQLITE_FCNTL_FILESTAT
const SQLITE_FCNTL_FILESTAT = 45

//so:extern SQLITE_FCNTL_FILE_POINTER
const SQLITE_FCNTL_FILE_POINTER = 7

//so:extern SQLITE_FCNTL_GET_LOCKPROXYFILE
const SQLITE_FCNTL_GET_LOCKPROXYFILE = 2

//so:extern SQLITE_FCNTL_HAS_MOVED
const SQLITE_FCNTL_HAS_MOVED = 20

//so:extern SQLITE_FCNTL_JOURNAL_POINTER
const SQLITE_FCNTL_JOURNAL_POINTER = 28

//so:extern SQLITE_FCNTL_LAST_ERRNO
const SQLITE_FCNTL_LAST_ERRNO = 4

//so:extern SQLITE_FCNTL_LOCKSTATE
const SQLITE_FCNTL_LOCKSTATE = 1

//so:extern SQLITE_FCNTL_LOCK_TIMEOUT
const SQLITE_FCNTL_LOCK_TIMEOUT = 34

//so:extern SQLITE_FCNTL_MMAP_SIZE
const SQLITE_FCNTL_MMAP_SIZE = 18

//so:extern SQLITE_FCNTL_NULL_IO
const SQLITE_FCNTL_NULL_IO = 43

//so:extern SQLITE_FCNTL_OVERWRITE
const SQLITE_FCNTL_OVERWRITE = 11

//so:extern SQLITE_FCNTL_PDB
const SQLITE_FCNTL_PDB = 30

//so:extern SQLITE_FCNTL_PERSIST_WAL
const SQLITE_FCNTL_PERSIST_WAL = 10

//so:extern SQLITE_FCNTL_POWERSAFE_OVERWRITE
const SQLITE_FCNTL_POWERSAFE_OVERWRITE = 13

//so:extern SQLITE_FCNTL_PRAGMA
const SQLITE_FCNTL_PRAGMA = 14

//so:extern SQLITE_FCNTL_RBU
const SQLITE_FCNTL_RBU = 26

//so:extern SQLITE_FCNTL_RESERVE_BYTES
const SQLITE_FCNTL_RESERVE_BYTES = 38

//so:extern SQLITE_FCNTL_RESET_CACHE
const SQLITE_FCNTL_RESET_CACHE = 42

//so:extern SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE
const SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE = 33

//so:extern SQLITE_FCNTL_SET_LOCKPROXYFILE
const SQLITE_FCNTL_SET_LOCKPROXYFILE = 3

//so:extern SQLITE_FCNTL_SIZE_HINT
const SQLITE_FCNTL_SIZE_HINT = 5

//so:extern SQLITE_FCNTL_SIZE_LIMIT
const SQLITE_FCNTL_SIZE_LIMIT = 36

//so:extern SQLITE_FCNTL_SYNC
const SQLITE_FCNTL_SYNC = 21

//so:extern SQLITE_FCNTL_SYNC_OMITTED
const SQLITE_FCNTL_SYNC_OMITTED = 8

//so:extern SQLITE_FCNTL_TEMPFILENAME
const SQLITE_FCNTL_TEMPFILENAME = 16

//so:extern SQLITE_FCNTL_TRACE
const SQLITE_FCNTL_TRACE = 19

//so:extern SQLITE_FCNTL_VFSNAME
const SQLITE_FCNTL_VFSNAME = 12

//so:extern SQLITE_FCNTL_VFS_POINTER
const SQLITE_FCNTL_VFS_POINTER = 27

//so:extern SQLITE_FCNTL_WAL_BLOCK
const SQLITE_FCNTL_WAL_BLOCK = 24

//so:extern SQLITE_FCNTL_WIN32_AV_RETRY
const SQLITE_FCNTL_WIN32_AV_RETRY = 9

//so:extern SQLITE_FCNTL_WIN32_GET_HANDLE
const SQLITE_FCNTL_WIN32_GET_HANDLE = 29

//so:extern SQLITE_FCNTL_WIN32_SET_HANDLE
const SQLITE_FCNTL_WIN32_SET_HANDLE = 23

//so:extern SQLITE_FCNTL_ZIPVFS
const SQLITE_FCNTL_ZIPVFS = 25

//so:extern SQLITE_FLOAT
const SQLITE_FLOAT = 2

//so:extern SQLITE_FORMAT
const SQLITE_FORMAT = 24

//so:extern SQLITE_FULL
const SQLITE_FULL = 13

//so:extern SQLITE_FUNCTION
const SQLITE_FUNCTION = 31

//so:extern SQLITE_GET_LOCKPROXYFILE
const SQLITE_GET_LOCKPROXYFILE = 2

//so:extern SQLITE_IGNORE
const SQLITE_IGNORE = 2

//so:extern SQLITE_INDEX_CONSTRAINT_EQ
const SQLITE_INDEX_CONSTRAINT_EQ = 2

//so:extern SQLITE_INDEX_CONSTRAINT_FUNCTION
const SQLITE_INDEX_CONSTRAINT_FUNCTION = 150

//so:extern SQLITE_INDEX_CONSTRAINT_GE
const SQLITE_INDEX_CONSTRAINT_GE = 32

//so:extern SQLITE_INDEX_CONSTRAINT_GLOB
const SQLITE_INDEX_CONSTRAINT_GLOB = 66

//so:extern SQLITE_INDEX_CONSTRAINT_GT
const SQLITE_INDEX_CONSTRAINT_GT = 4

//so:extern SQLITE_INDEX_CONSTRAINT_IS
const SQLITE_INDEX_CONSTRAINT_IS = 72

//so:extern SQLITE_INDEX_CONSTRAINT_ISNOT
const SQLITE_INDEX_CONSTRAINT_ISNOT = 69

//so:extern SQLITE_INDEX_CONSTRAINT_ISNOTNULL
const SQLITE_INDEX_CONSTRAINT_ISNOTNULL = 70

//so:extern SQLITE_INDEX_CONSTRAINT_ISNULL
const SQLITE_INDEX_CONSTRAINT_ISNULL = 71

//so:extern SQLITE_INDEX_CONSTRAINT_LE
const SQLITE_INDEX_CONSTRAINT_LE = 8

//so:extern SQLITE_INDEX_CONSTRAINT_LIKE
const SQLITE_INDEX_CONSTRAINT_LIKE = 65

//so:extern SQLITE_INDEX_CONSTRAINT_LIMIT
const SQLITE_INDEX_CONSTRAINT_LIMIT = 73

//so:extern SQLITE_INDEX_CONSTRAINT_LT
const SQLITE_INDEX_CONSTRAINT_LT = 16

//so:extern SQLITE_INDEX_CONSTRAINT_MATCH
const SQLITE_INDEX_CONSTRAINT_MATCH = 64

//so:extern SQLITE_INDEX_CONSTRAINT_NE
const SQLITE_INDEX_CONSTRAINT_NE = 68

//so:extern SQLITE_INDEX_CONSTRAINT_OFFSET
const SQLITE_INDEX_CONSTRAINT_OFFSET = 74

//so:extern SQLITE_INDEX_CONSTRAINT_REGEXP
const SQLITE_INDEX_CONSTRAINT_REGEXP = 67

//so:extern SQLITE_INDEX_SCAN_HEX
const SQLITE_INDEX_SCAN_HEX = 2

//so:extern SQLITE_INDEX_SCAN_UNIQUE
const SQLITE_INDEX_SCAN_UNIQUE = 1

//so:extern SQLITE_INNOCUOUS
const SQLITE_INNOCUOUS = 2097152

//so:extern SQLITE_INSERT
const SQLITE_INSERT = 18

//so:extern SQLITE_INTEGER
const SQLITE_INTEGER = 1

//so:extern SQLITE_INTERNAL
const SQLITE_INTERNAL = 2

//so:extern SQLITE_INTERRUPT
const SQLITE_INTERRUPT = 9

//so:extern SQLITE_IOCAP_ATOMIC
const SQLITE_IOCAP_ATOMIC = 1

//so:extern SQLITE_IOCAP_ATOMIC16K
const SQLITE_IOCAP_ATOMIC16K = 64

//so:extern SQLITE_IOCAP_ATOMIC1K
const SQLITE_IOCAP_ATOMIC1K = 4

//so:extern SQLITE_IOCAP_ATOMIC2K
const SQLITE_IOCAP_ATOMIC2K = 8

//so:extern SQLITE_IOCAP_ATOMIC32K
const SQLITE_IOCAP_ATOMIC32K = 128

//so:extern SQLITE_IOCAP_ATOMIC4K
const SQLITE_IOCAP_ATOMIC4K = 16

//so:extern SQLITE_IOCAP_ATOMIC512
const SQLITE_IOCAP_ATOMIC512 = 2

//so:extern SQLITE_IOCAP_ATOMIC64K
const SQLITE_IOCAP_ATOMIC64K = 256

//so:extern SQLITE_IOCAP_ATOMIC8K
const SQLITE_IOCAP_ATOMIC8K = 32

//so:extern SQLITE_IOCAP_BATCH_ATOMIC
const SQLITE_IOCAP_BATCH_ATOMIC = 16384

//so:extern SQLITE_IOCAP_IMMUTABLE
const SQLITE_IOCAP_IMMUTABLE = 8192

//so:extern SQLITE_IOCAP_POWERSAFE_OVERWRITE
const SQLITE_IOCAP_POWERSAFE_OVERWRITE = 4096

//so:extern SQLITE_IOCAP_SAFE_APPEND
const SQLITE_IOCAP_SAFE_APPEND = 512

//so:extern SQLITE_IOCAP_SEQUENTIAL
const SQLITE_IOCAP_SEQUENTIAL = 1024

//so:extern SQLITE_IOCAP_SUBPAGE_READ
const SQLITE_IOCAP_SUBPAGE_READ = 32768

//so:extern SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN
const SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN = 2048

//so:extern SQLITE_IOERR
const SQLITE_IOERR = 10

//so:extern SQLITE_IOERR_ACCESS
const SQLITE_IOERR_ACCESS = 3338

//so:extern SQLITE_IOERR_AUTH
const SQLITE_IOERR_AUTH = 7178

//so:extern SQLITE_IOERR_BADKEY
const SQLITE_IOERR_BADKEY = 8970

//so:extern SQLITE_IOERR_BEGIN_ATOMIC
const SQLITE_IOERR_BEGIN_ATOMIC = 7434

//so:extern SQLITE_IOERR_BLOCKED
const SQLITE_IOERR_BLOCKED = 2826

//so:extern SQLITE_IOERR_CHECKRESERVEDLOCK
const SQLITE_IOERR_CHECKRESERVEDLOCK = 3594

//so:extern SQLITE_IOERR_CLOSE
const SQLITE_IOERR_CLOSE = 4106

//so:extern SQLITE_IOERR_CODEC
const SQLITE_IOERR_CODEC = 9226

//so:extern SQLITE_IOERR_COMMIT_ATOMIC
const SQLITE_IOERR_COMMIT_ATOMIC = 7690

//so:extern SQLITE_IOERR_CONVPATH
const SQLITE_IOERR_CONVPATH = 6666

//so:extern SQLITE_IOERR_CORRUPTFS
const SQLITE_IOERR_CORRUPTFS = 8458

//so:extern SQLITE_IOERR_DATA
const SQLITE_IOERR_DATA = 8202

//so:extern SQLITE_IOERR_DELETE
const SQLITE_IOERR_DELETE = 2570

//so:extern SQLITE_IOERR_DELETE_NOENT
const SQLITE_IOERR_DELETE_NOENT = 5898

//so:extern SQLITE_IOERR_DIR_CLOSE
const SQLITE_IOERR_DIR_CLOSE = 4362

//so:extern SQLITE_IOERR_DIR_FSYNC
const SQLITE_IOERR_DIR_FSYNC = 1290

//so:extern SQLITE_IOERR_FSTAT
const SQLITE_IOERR_FSTAT = 1802

//so:extern SQLITE_IOERR_FSYNC
const SQLITE_IOERR_FSYNC = 1034

//so:extern SQLITE_IOERR_GETTEMPPATH
const SQLITE_IOERR_GETTEMPPATH = 6410

//so:extern SQLITE_IOERR_IN_PAGE
const SQLITE_IOERR_IN_PAGE = 8714

//so:extern SQLITE_IOERR_LOCK
const SQLITE_IOERR_LOCK = 3850

//so:extern SQLITE_IOERR_MMAP
const SQLITE_IOERR_MMAP = 6154

//so:extern SQLITE_IOERR_NOMEM
const SQLITE_IOERR_NOMEM = 3082

//so:extern SQLITE_IOERR_RDLOCK
const SQLITE_IOERR_RDLOCK = 2314

//so:extern SQLITE_IOERR_READ
const SQLITE_IOERR_READ = 266

//so:extern SQLITE_IOERR_ROLLBACK_ATOMIC
const SQLITE_IOERR_ROLLBACK_ATOMIC = 7946

//so:extern SQLITE_IOERR_SEEK
const SQLITE_IOERR_SEEK = 5642

//so:extern SQLITE_IOERR_SHMLOCK
const SQLITE_IOERR_SHMLOCK = 5130

//so:extern SQLITE_IOERR_SHMMAP
const SQLITE_IOERR_SHMMAP = 5386

//so:extern SQLITE_IOERR_SHMOPEN
const SQLITE_IOERR_SHMOPEN = 4618

//so:extern SQLITE_IOERR_SHMSIZE
const SQLITE_IOERR_SHMSIZE = 4874

//so:extern SQLITE_IOERR_SHORT_READ
const SQLITE_IOERR_SHORT_READ = 522

//so:extern SQLITE_IOERR_TRUNCATE
const SQLITE_IOERR_TRUNCATE = 1546

//so:extern SQLITE_IOERR_UNLOCK
const SQLITE_IOERR_UNLOCK = 2058

//so:extern SQLITE_IOERR_VNODE
const SQLITE_IOERR_VNODE = 6922

//so:extern SQLITE_IOERR_WRITE
const SQLITE_IOERR_WRITE = 778

//so:extern SQLITE_LAST_ERRNO
const SQLITE_LAST_ERRNO = 4

//so:extern SQLITE_LIMIT_ATTACHED
const SQLITE_LIMIT_ATTACHED = 7

//so:extern SQLITE_LIMIT_COLUMN
const SQLITE_LIMIT_COLUMN = 2

//so:extern SQLITE_LIMIT_COMPOUND_SELECT
const SQLITE_LIMIT_COMPOUND_SELECT = 4

//so:extern SQLITE_LIMIT_EXPR_DEPTH
const SQLITE_LIMIT_EXPR_DEPTH = 3

//so:extern SQLITE_LIMIT_FUNCTION_ARG
const SQLITE_LIMIT_FUNCTION_ARG = 6

//so:extern SQLITE_LIMIT_LENGTH
const SQLITE_LIMIT_LENGTH = 0

//so:extern SQLITE_LIMIT_LIKE_PATTERN_LENGTH
const SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8

//so:extern SQLITE_LIMIT_PARSER_DEPTH
const SQLITE_LIMIT_PARSER_DEPTH = 12

//so:extern SQLITE_LIMIT_SQL_LENGTH
const SQLITE_LIMIT_SQL_LENGTH = 1

//so:extern SQLITE_LIMIT_TRIGGER_DEPTH
const SQLITE_LIMIT_TRIGGER_DEPTH = 10

//so:extern SQLITE_LIMIT_VARIABLE_NUMBER
const SQLITE_LIMIT_VARIABLE_NUMBER = 9

//so:extern SQLITE_LIMIT_VDBE_OP
const SQLITE_LIMIT_VDBE_OP = 5

//so:extern SQLITE_LIMIT_WORKER_THREADS
const SQLITE_LIMIT_WORKER_THREADS = 11

//so:extern SQLITE_LOCKED
const SQLITE_LOCKED = 6

//so:extern SQLITE_LOCKED_SHAREDCACHE
const SQLITE_LOCKED_SHAREDCACHE = 262

//so:extern SQLITE_LOCKED_VTAB
const SQLITE_LOCKED_VTAB = 518

//so:extern SQLITE_LOCK_EXCLUSIVE
const SQLITE_LOCK_EXCLUSIVE = 4

//so:extern SQLITE_LOCK_NONE
const SQLITE_LOCK_NONE = 0

//so:extern SQLITE_LOCK_PENDING
const SQLITE_LOCK_PENDING = 3

//so:extern SQLITE_LOCK_RESERVED
const SQLITE_LOCK_RESERVED = 2

//so:extern SQLITE_LOCK_SHARED
const SQLITE_LOCK_SHARED = 1

//so:extern SQLITE_MISMATCH
const SQLITE_MISMATCH = 20

//so:extern SQLITE_MISUSE
const SQLITE_MISUSE = 21

//so:extern SQLITE_MUTEX_FAST
const SQLITE_MUTEX_FAST = 0

//so:extern SQLITE_MUTEX_RECURSIVE
const SQLITE_MUTEX_RECURSIVE = 1

//so:extern SQLITE_MUTEX_STATIC_APP1
const SQLITE_MUTEX_STATIC_APP1 = 8

//so:extern SQLITE_MUTEX_STATIC_APP2
const SQLITE_MUTEX_STATIC_APP2 = 9

//so:extern SQLITE_MUTEX_STATIC_APP3
const SQLITE_MUTEX_STATIC_APP3 = 10

//so:extern SQLITE_MUTEX_STATIC_LRU
const SQLITE_MUTEX_STATIC_LRU = 6

//so:extern SQLITE_MUTEX_STATIC_LRU2
const SQLITE_MUTEX_STATIC_LRU2 = 7

//so:extern SQLITE_MUTEX_STATIC_MAIN
const SQLITE_MUTEX_STATIC_MAIN = 2

//so:extern SQLITE_MUTEX_STATIC_MASTER
const SQLITE_MUTEX_STATIC_MASTER = 2

//so:extern SQLITE_MUTEX_STATIC_MEM
const SQLITE_MUTEX_STATIC_MEM = 3

//so:extern SQLITE_MUTEX_STATIC_MEM2
const SQLITE_MUTEX_STATIC_MEM2 = 4

//so:extern SQLITE_MUTEX_STATIC_OPEN
const SQLITE_MUTEX_STATIC_OPEN = 4

//so:extern SQLITE_MUTEX_STATIC_PMEM
const SQLITE_MUTEX_STATIC_PMEM = 7

//so:extern SQLITE_MUTEX_STATIC_PRNG
const SQLITE_MUTEX_STATIC_PRNG = 5

//so:extern SQLITE_MUTEX_STATIC_VFS1
const SQLITE_MUTEX_STATIC_VFS1 = 11

//so:extern SQLITE_MUTEX_STATIC_VFS2
const SQLITE_MUTEX_STATIC_VFS2 = 12

//so:extern SQLITE_MUTEX_STATIC_VFS3
const SQLITE_MUTEX_STATIC_VFS3 = 13

//so:extern SQLITE_NOLFS
const SQLITE_NOLFS = 22

//so:extern SQLITE_NOMEM
const SQLITE_NOMEM = 7

//so:extern SQLITE_NOTADB
const SQLITE_NOTADB = 26

//so:extern SQLITE_NOTFOUND
const SQLITE_NOTFOUND = 12

//so:extern SQLITE_NOTICE
const SQLITE_NOTICE = 27

//so:extern SQLITE_NOTICE_RBU
const SQLITE_NOTICE_RBU = 795

//so:extern SQLITE_NOTICE_RECOVER_ROLLBACK
const SQLITE_NOTICE_RECOVER_ROLLBACK = 539

//so:extern SQLITE_NOTICE_RECOVER_WAL
const SQLITE_NOTICE_RECOVER_WAL = 283

//so:extern SQLITE_NULL
const SQLITE_NULL = 5

//so:extern SQLITE_OK
const SQLITE_OK = 0

//so:extern SQLITE_OK_LOAD_PERMANENTLY
const SQLITE_OK_LOAD_PERMANENTLY = 256

//so:extern SQLITE_OK_SYMLINK
const SQLITE_OK_SYMLINK = 512

//so:extern SQLITE_OPEN_AUTOPROXY
const SQLITE_OPEN_AUTOPROXY = 32

//so:extern SQLITE_OPEN_CREATE
const SQLITE_OPEN_CREATE = 4

//so:extern SQLITE_OPEN_DELETEONCLOSE
const SQLITE_OPEN_DELETEONCLOSE = 8

//so:extern SQLITE_OPEN_EXCLUSIVE
const SQLITE_OPEN_EXCLUSIVE = 16

//so:extern SQLITE_OPEN_EXRESCODE
const SQLITE_OPEN_EXRESCODE = 33554432

//so:extern SQLITE_OPEN_FULLMUTEX
const SQLITE_OPEN_FULLMUTEX = 65536

//so:extern SQLITE_OPEN_MAIN_DB
const SQLITE_OPEN_MAIN_DB = 256

//so:extern SQLITE_OPEN_MAIN_JOURNAL
const SQLITE_OPEN_MAIN_JOURNAL = 2048

//so:extern SQLITE_OPEN_MASTER_JOURNAL
const SQLITE_OPEN_MASTER_JOURNAL = 16384

//so:extern SQLITE_OPEN_MEMORY
const SQLITE_OPEN_MEMORY = 128

//so:extern SQLITE_OPEN_NOFOLLOW
const SQLITE_OPEN_NOFOLLOW = 16777216

//so:extern SQLITE_OPEN_NOMUTEX
const SQLITE_OPEN_NOMUTEX = 32768

//so:extern SQLITE_OPEN_PRIVATECACHE
const SQLITE_OPEN_PRIVATECACHE = 262144

//so:extern SQLITE_OPEN_READONLY
const SQLITE_OPEN_READONLY = 1

//so:extern SQLITE_OPEN_READWRITE
const SQLITE_OPEN_READWRITE = 2

//so:extern SQLITE_OPEN_SHAREDCACHE
const SQLITE_OPEN_SHAREDCACHE = 131072

//so:extern SQLITE_OPEN_SUBJOURNAL
const SQLITE_OPEN_SUBJOURNAL = 8192

//so:extern SQLITE_OPEN_SUPER_JOURNAL
const SQLITE_OPEN_SUPER_JOURNAL = 16384

//so:extern SQLITE_OPEN_TEMP_DB
const SQLITE_OPEN_TEMP_DB = 512

//so:extern SQLITE_OPEN_TEMP_JOURNAL
const SQLITE_OPEN_TEMP_JOURNAL = 4096

//so:extern SQLITE_OPEN_TRANSIENT_DB
const SQLITE_OPEN_TRANSIENT_DB = 1024

//so:extern SQLITE_OPEN_URI
const SQLITE_OPEN_URI = 64

//so:extern SQLITE_OPEN_WAL
const SQLITE_OPEN_WAL = 524288

//so:extern SQLITE_PERM
const SQLITE_PERM = 3

//so:extern SQLITE_PRAGMA
const SQLITE_PRAGMA = 19

//so:extern SQLITE_PREPARE_DONT_LOG
const SQLITE_PREPARE_DONT_LOG = 16

//so:extern SQLITE_PREPARE_FROM_DDL
const SQLITE_PREPARE_FROM_DDL = 32

//so:extern SQLITE_PREPARE_NORMALIZE
const SQLITE_PREPARE_NORMALIZE = 2

//so:extern SQLITE_PREPARE_NO_VTAB
const SQLITE_PREPARE_NO_VTAB = 4

//so:extern SQLITE_PREPARE_PERSISTENT
const SQLITE_PREPARE_PERSISTENT = 1

//so:extern SQLITE_PROTOCOL
const SQLITE_PROTOCOL = 15

//so:extern SQLITE_RANGE
const SQLITE_RANGE = 25

//so:extern SQLITE_READ
const SQLITE_READ = 20

//so:extern SQLITE_READONLY
const SQLITE_READONLY = 8

//so:extern SQLITE_READONLY_CANTINIT
const SQLITE_READONLY_CANTINIT = 1288

//so:extern SQLITE_READONLY_CANTLOCK
const SQLITE_READONLY_CANTLOCK = 520

//so:extern SQLITE_READONLY_DBMOVED
const SQLITE_READONLY_DBMOVED = 1032

//so:extern SQLITE_READONLY_DIRECTORY
const SQLITE_READONLY_DIRECTORY = 1544

//so:extern SQLITE_READONLY_RECOVERY
const SQLITE_READONLY_RECOVERY = 264

//so:extern SQLITE_READONLY_ROLLBACK
const SQLITE_READONLY_ROLLBACK = 776

//so:extern SQLITE_RECURSIVE
const SQLITE_RECURSIVE = 33

//so:extern SQLITE_REINDEX
const SQLITE_REINDEX = 27

//so:extern SQLITE_REPLACE
const SQLITE_REPLACE = 5

//so:extern SQLITE_RESULT_SUBTYPE
const SQLITE_RESULT_SUBTYPE = 16777216

//so:extern SQLITE_ROLLBACK
const SQLITE_ROLLBACK = 1

//so:extern SQLITE_ROW
const SQLITE_ROW = 100

//so:extern SQLITE_SAVEPOINT
const SQLITE_SAVEPOINT = 32

//so:extern SQLITE_SCANSTAT_COMPLEX
const SQLITE_SCANSTAT_COMPLEX = 1

//so:extern SQLITE_SCANSTAT_EST
const SQLITE_SCANSTAT_EST = 2

//so:extern SQLITE_SCANSTAT_EXPLAIN
const SQLITE_SCANSTAT_EXPLAIN = 4

//so:extern SQLITE_SCANSTAT_NAME
const SQLITE_SCANSTAT_NAME = 3

//so:extern SQLITE_SCANSTAT_NCYCLE
const SQLITE_SCANSTAT_NCYCLE = 7

//so:extern SQLITE_SCANSTAT_NLOOP
const SQLITE_SCANSTAT_NLOOP = 0

//so:extern SQLITE_SCANSTAT_NVISIT
const SQLITE_SCANSTAT_NVISIT = 1

//so:extern SQLITE_SCANSTAT_PARENTID
const SQLITE_SCANSTAT_PARENTID = 6

//so:extern SQLITE_SCANSTAT_SELECTID
const SQLITE_SCANSTAT_SELECTID = 5

//so:extern SQLITE_SCHEMA
const SQLITE_SCHEMA = 17

//so:extern SQLITE_SELECT
const SQLITE_SELECT = 21

//so:extern SQLITE_SELFORDER1
const SQLITE_SELFORDER1 = 33554432

//so:extern SQLITE_SERIALIZE_NOCOPY
const SQLITE_SERIALIZE_NOCOPY = 1

//so:extern SQLITE_SETLK_BLOCK_ON_CONNECT
const SQLITE_SETLK_BLOCK_ON_CONNECT = 1

//so:extern SQLITE_SET_LOCKPROXYFILE
const SQLITE_SET_LOCKPROXYFILE = 3

//so:extern SQLITE_SHM_EXCLUSIVE
const SQLITE_SHM_EXCLUSIVE = 8

//so:extern SQLITE_SHM_LOCK
const SQLITE_SHM_LOCK = 2

//so:extern SQLITE_SHM_NLOCK
const SQLITE_SHM_NLOCK = 8

//so:extern SQLITE_SHM_SHARED
const SQLITE_SHM_SHARED = 4

//so:extern SQLITE_SHM_UNLOCK
const SQLITE_SHM_UNLOCK = 1

//so:extern SQLITE_STATUS_MALLOC_COUNT
const SQLITE_STATUS_MALLOC_COUNT = 9

//so:extern SQLITE_STATUS_MALLOC_SIZE
const SQLITE_STATUS_MALLOC_SIZE = 5

//so:extern SQLITE_STATUS_MEMORY_USED
const SQLITE_STATUS_MEMORY_USED = 0

//so:extern SQLITE_STATUS_PAGECACHE_OVERFLOW
const SQLITE_STATUS_PAGECACHE_OVERFLOW = 2

//so:extern SQLITE_STATUS_PAGECACHE_SIZE
const SQLITE_STATUS_PAGECACHE_SIZE = 7

//so:extern SQLITE_STATUS_PAGECACHE_USED
const SQLITE_STATUS_PAGECACHE_USED = 1

//so:extern SQLITE_STATUS_PARSER_STACK
const SQLITE_STATUS_PARSER_STACK = 6

//so:extern SQLITE_STATUS_SCRATCH_OVERFLOW
const SQLITE_STATUS_SCRATCH_OVERFLOW = 4

//so:extern SQLITE_STATUS_SCRATCH_SIZE
const SQLITE_STATUS_SCRATCH_SIZE = 8

//so:extern SQLITE_STATUS_SCRATCH_USED
const SQLITE_STATUS_SCRATCH_USED = 3

//so:extern SQLITE_STMTSTATUS_AUTOINDEX
const SQLITE_STMTSTATUS_AUTOINDEX = 3

//so:extern SQLITE_STMTSTATUS_FILTER_HIT
const SQLITE_STMTSTATUS_FILTER_HIT = 8

//so:extern SQLITE_STMTSTATUS_FILTER_MISS
const SQLITE_STMTSTATUS_FILTER_MISS = 7

//so:extern SQLITE_STMTSTATUS_FULLSCAN_STEP
const SQLITE_STMTSTATUS_FULLSCAN_STEP = 1

//so:extern SQLITE_STMTSTATUS_MEMUSED
const SQLITE_STMTSTATUS_MEMUSED = 99

//so:extern SQLITE_STMTSTATUS_REPREPARE
const SQLITE_STMTSTATUS_REPREPARE = 5

//so:extern SQLITE_STMTSTATUS_RUN
const SQLITE_STMTSTATUS_RUN = 6

//so:extern SQLITE_STMTSTATUS_SORT
const SQLITE_STMTSTATUS_SORT = 2

//so:extern SQLITE_STMTSTATUS_VM_STEP
const SQLITE_STMTSTATUS_VM_STEP = 4

//so:extern SQLITE_SUBTYPE
const SQLITE_SUBTYPE = 1048576

//so:extern SQLITE_SYNC_DATAONLY
const SQLITE_SYNC_DATAONLY = 16

//so:extern SQLITE_SYNC_FULL
const SQLITE_SYNC_FULL = 3

//so:extern SQLITE_SYNC_NORMAL
const SQLITE_SYNC_NORMAL = 2

//so:extern SQLITE_TESTCTRL_ALWAYS
const SQLITE_TESTCTRL_ALWAYS = 13

//so:extern SQLITE_TESTCTRL_ASSERT
const SQLITE_TESTCTRL_ASSERT = 12

//so:extern SQLITE_TESTCTRL_ATOF
const SQLITE_TESTCTRL_ATOF = 34

//so:extern SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS
const SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS = 10

//so:extern SQLITE_TESTCTRL_BITVEC_TEST
const SQLITE_TESTCTRL_BITVEC_TEST = 8

//so:extern SQLITE_TESTCTRL_BYTEORDER
const SQLITE_TESTCTRL_BYTEORDER = 22

//so:extern SQLITE_TESTCTRL_EXPLAIN_STMT
const SQLITE_TESTCTRL_EXPLAIN_STMT = 19

//so:extern SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS
const SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS = 29

//so:extern SQLITE_TESTCTRL_FAULT_INSTALL
const SQLITE_TESTCTRL_FAULT_INSTALL = 9

//so:extern SQLITE_TESTCTRL_FIRST
const SQLITE_TESTCTRL_FIRST = 5

//so:extern SQLITE_TESTCTRL_FK_NO_ACTION
const SQLITE_TESTCTRL_FK_NO_ACTION = 7

//so:extern SQLITE_TESTCTRL_GETOPT
const SQLITE_TESTCTRL_GETOPT = 16

//so:extern SQLITE_TESTCTRL_IMPOSTER
const SQLITE_TESTCTRL_IMPOSTER = 25

//so:extern SQLITE_TESTCTRL_INTERNAL_FUNCTIONS
const SQLITE_TESTCTRL_INTERNAL_FUNCTIONS = 17

//so:extern SQLITE_TESTCTRL_ISINIT
const SQLITE_TESTCTRL_ISINIT = 23

//so:extern SQLITE_TESTCTRL_ISKEYWORD
const SQLITE_TESTCTRL_ISKEYWORD = 16

//so:extern SQLITE_TESTCTRL_JSON_SELFCHECK
const SQLITE_TESTCTRL_JSON_SELFCHECK = 14

//so:extern SQLITE_TESTCTRL_LAST
const SQLITE_TESTCTRL_LAST = 34

//so:extern SQLITE_TESTCTRL_LOCALTIME_FAULT
const SQLITE_TESTCTRL_LOCALTIME_FAULT = 18

//so:extern SQLITE_TESTCTRL_LOGEST
const SQLITE_TESTCTRL_LOGEST = 33

//so:extern SQLITE_TESTCTRL_NEVER_CORRUPT
const SQLITE_TESTCTRL_NEVER_CORRUPT = 20

//so:extern SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD
const SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD = 19

//so:extern SQLITE_TESTCTRL_OPTIMIZATIONS
const SQLITE_TESTCTRL_OPTIMIZATIONS = 15

//so:extern SQLITE_TESTCTRL_PARSER_COVERAGE
const SQLITE_TESTCTRL_PARSER_COVERAGE = 26

//so:extern SQLITE_TESTCTRL_PENDING_BYTE
const SQLITE_TESTCTRL_PENDING_BYTE = 11

//so:extern SQLITE_TESTCTRL_PRNG_RESET
const SQLITE_TESTCTRL_PRNG_RESET = 7

//so:extern SQLITE_TESTCTRL_PRNG_RESTORE
const SQLITE_TESTCTRL_PRNG_RESTORE = 6

//so:extern SQLITE_TESTCTRL_PRNG_SAVE
const SQLITE_TESTCTRL_PRNG_SAVE = 5

//so:extern SQLITE_TESTCTRL_PRNG_SEED
const SQLITE_TESTCTRL_PRNG_SEED = 28

//so:extern SQLITE_TESTCTRL_RESERVE
const SQLITE_TESTCTRL_RESERVE = 14

//so:extern SQLITE_TESTCTRL_RESULT_INTREAL
const SQLITE_TESTCTRL_RESULT_INTREAL = 27

//so:extern SQLITE_TESTCTRL_SCRATCHMALLOC
const SQLITE_TESTCTRL_SCRATCHMALLOC = 17

//so:extern SQLITE_TESTCTRL_SEEK_COUNT
const SQLITE_TESTCTRL_SEEK_COUNT = 30

//so:extern SQLITE_TESTCTRL_SORTER_MMAP
const SQLITE_TESTCTRL_SORTER_MMAP = 24

//so:extern SQLITE_TESTCTRL_TRACEFLAGS
const SQLITE_TESTCTRL_TRACEFLAGS = 31

//so:extern SQLITE_TESTCTRL_TUNE
const SQLITE_TESTCTRL_TUNE = 32

//so:extern SQLITE_TESTCTRL_USELONGDOUBLE
const SQLITE_TESTCTRL_USELONGDOUBLE = 34

//so:extern SQLITE_TESTCTRL_VDBE_COVERAGE
const SQLITE_TESTCTRL_VDBE_COVERAGE = 21

//so:extern SQLITE_TEXT
const SQLITE_TEXT = 3

//so:extern SQLITE_TOOBIG
const SQLITE_TOOBIG = 18

//so:extern SQLITE_TRACE_CLOSE
const SQLITE_TRACE_CLOSE = 8

//so:extern SQLITE_TRACE_PROFILE
const SQLITE_TRACE_PROFILE = 2

//so:extern SQLITE_TRACE_ROW
const SQLITE_TRACE_ROW = 4

//so:extern SQLITE_TRACE_STMT
const SQLITE_TRACE_STMT = 1

//so:extern SQLITE_TRANSACTION
const SQLITE_TRANSACTION = 22

//so:extern SQLITE_TXN_NONE
const SQLITE_TXN_NONE = 0

//so:extern SQLITE_TXN_READ
const SQLITE_TXN_READ = 1

//so:extern SQLITE_TXN_WRITE
const SQLITE_TXN_WRITE = 2

//so:extern SQLITE_UPDATE
const SQLITE_UPDATE = 23

//so:extern SQLITE_UTF16
const SQLITE_UTF16 = 4

//so:extern SQLITE_UTF16BE
const SQLITE_UTF16BE = 3

//so:extern SQLITE_UTF16LE
const SQLITE_UTF16LE = 2

//so:extern SQLITE_UTF16_ALIGNED
const SQLITE_UTF16_ALIGNED = 8

//so:extern SQLITE_UTF8
const SQLITE_UTF8 = 1

//so:extern SQLITE_UTF8_ZT
const SQLITE_UTF8_ZT = 16

//so:extern SQLITE_VERSION_NUMBER
const SQLITE_VERSION_NUMBER = 3053004

//so:extern SQLITE_VTAB_CONSTRAINT_SUPPORT
const SQLITE_VTAB_CONSTRAINT_SUPPORT = 1

//so:extern SQLITE_VTAB_DIRECTONLY
const SQLITE_VTAB_DIRECTONLY = 3

//so:extern SQLITE_VTAB_INNOCUOUS
const SQLITE_VTAB_INNOCUOUS = 2

//so:extern SQLITE_VTAB_USES_ALL_SCHEMAS
const SQLITE_VTAB_USES_ALL_SCHEMAS = 4

//so:extern SQLITE_WARNING
const SQLITE_WARNING = 28

//so:extern SQLITE_WARNING_AUTOINDEX
const SQLITE_WARNING_AUTOINDEX = 284

//so:extern SQLITE_WIN32_DATA_DIRECTORY_TYPE
const SQLITE_WIN32_DATA_DIRECTORY_TYPE = 1

//so:extern SQLITE_WIN32_TEMP_DIRECTORY_TYPE
const SQLITE_WIN32_TEMP_DIRECTORY_TYPE = 2

// sobind: skipped sqlite3_version, the type is unmappable

//so:extern sqlite3_temp_directory
var Temp_directory *c.Char

//so:extern sqlite3_data_directory
var Data_directory *c.Char

//so:extern SQLITE_SCM_BRANCH
var SQLITE_SCM_BRANCH *c.ConstChar // "branch-3.53"

//so:extern SQLITE_SCM_DATETIME
var SQLITE_SCM_DATETIME *c.ConstChar // "2026-07-24T19:02:57.525Z"

//so:extern SQLITE_SCM_TAGS
var SQLITE_SCM_TAGS *c.ConstChar // "release version-3.53.4"

//so:extern SQLITE_SOURCE_ID
var SQLITE_SOURCE_ID *c.ConstChar // "2026-07-24 19:02:57 bf7c7f30031888f4e796e429ab3978879485813aaca6f641c7b33e4e09459bcc"

//so:extern SQLITE_VERSION
var SQLITE_VERSION *c.ConstChar // "3.53.4"

//so:extern sqlite3_libversion
func Libversion() *c.ConstChar

//so:extern sqlite3_sourceid
func Sourceid() *c.ConstChar

//so:extern sqlite3_libversion_number
func Libversion_number() c.Int

//so:extern sqlite3_compileoption_used
func Compileoption_used(zOptName string) c.Int

//so:extern sqlite3_compileoption_get
func Compileoption_get(N c.Int) *c.ConstChar

//so:extern sqlite3_threadsafe
func Threadsafe() c.Int

//so:extern sqlite3_close
func Close(arg0 *Sqlite3) c.Int

//so:extern sqlite3_close_v2
func Close_v2(arg0 *Sqlite3) c.Int

//so:extern sqlite3_exec
func Exec(arg0 *Sqlite3, sql string, callback func(any, c.Int, **c.Char, **c.Char) c.Int, arg3 any, errmsg **c.Char) c.Int

//so:extern sqlite3_initialize
func Initialize() c.Int

//so:extern sqlite3_shutdown
func Shutdown() c.Int

//so:extern sqlite3_os_init
func Os_init() c.Int

//so:extern sqlite3_os_end
func Os_end() c.Int

//so:extern sqlite3_config
func Config(arg0 c.Int, args ...any) c.Int

//so:extern sqlite3_db_config
func Db_config(arg0 *Sqlite3, op c.Int, args ...any) c.Int

//so:extern sqlite3_extended_result_codes
func Extended_result_codes(arg0 *Sqlite3, onoff c.Int) c.Int

//so:extern sqlite3_last_insert_rowid
func Last_insert_rowid(arg0 *Sqlite3) c.LongLong

//so:extern sqlite3_set_last_insert_rowid
func Set_last_insert_rowid(arg0 *Sqlite3, arg1 c.LongLong)

//so:extern sqlite3_changes
func Changes(arg0 *Sqlite3) c.Int

//so:extern sqlite3_changes64
func Changes64(arg0 *Sqlite3) c.LongLong

//so:extern sqlite3_total_changes
func Total_changes(arg0 *Sqlite3) c.Int

//so:extern sqlite3_total_changes64
func Total_changes64(arg0 *Sqlite3) c.LongLong

//so:extern sqlite3_interrupt
func Interrupt(arg0 *Sqlite3)

//so:extern sqlite3_is_interrupted
func Is_interrupted(arg0 *Sqlite3) c.Int

//so:extern sqlite3_complete
func Complete(sql string) c.Int

//so:extern sqlite3_complete16
func Complete16(sql any) c.Int

//so:extern sqlite3_busy_handler
func Busy_handler(arg0 *Sqlite3, arg1 func(any, c.Int) c.Int, arg2 any) c.Int

//so:extern sqlite3_busy_timeout
func Busy_timeout(arg0 *Sqlite3, ms c.Int) c.Int

//so:extern sqlite3_setlk_timeout
func Setlk_timeout(arg0 *Sqlite3, ms c.Int, flags c.Int) c.Int

//so:extern sqlite3_get_table
func Get_table(db *Sqlite3, zSql string, pazResult ***c.Char, pnRow *c.Int, pnColumn *c.Int, pzErrmsg **c.Char) c.Int

//so:extern sqlite3_free_table
func Free_table(result **c.Char)

//so:extern sqlite3_mprintf
func Mprintf(arg0 string, args ...any) *c.Char

//so:extern sqlite3_vmprintf
func Vmprintf(arg0 string, arg1 any) *c.Char

//so:extern sqlite3_snprintf
func Snprintf(arg0 c.Int, arg1 *c.Char, arg2 string, args ...any) *c.Char

//so:extern sqlite3_vsnprintf
func Vsnprintf(arg0 c.Int, arg1 *c.Char, arg2 string, arg3 any) *c.Char

//so:extern sqlite3_malloc
func Malloc(arg0 c.Int) any

//so:extern sqlite3_malloc64
func Malloc64(arg0 c.ULongLong) any

//so:extern sqlite3_realloc
func Realloc(arg0 any, arg1 c.Int) any

//so:extern sqlite3_realloc64
func Realloc64(arg0 any, arg1 c.ULongLong) any

//so:extern sqlite3_free
func Free(arg0 any)

//so:extern sqlite3_msize
func Msize(arg0 any) c.ULongLong

//so:extern sqlite3_memory_used
func Memory_used() c.LongLong

//so:extern sqlite3_memory_highwater
func Memory_highwater(resetFlag c.Int) c.LongLong

//so:extern sqlite3_randomness
func Randomness(N c.Int, P any)

//so:extern sqlite3_set_authorizer
func Set_authorizer(arg0 *Sqlite3, xAuth func(any, c.Int, *c.ConstChar, *c.ConstChar, *c.ConstChar, *c.ConstChar) c.Int, pUserData any) c.Int

//so:extern sqlite3_trace
func Trace(arg0 *Sqlite3, xTrace func(any, *c.ConstChar), arg2 any) any

//so:extern sqlite3_profile
func Profile(arg0 *Sqlite3, xProfile func(any, *c.ConstChar, c.ULongLong), arg2 any) any

//so:extern sqlite3_trace_v2
func Trace_v2(arg0 *Sqlite3, uMask c.UInt, xCallback func(c.UInt, any, any, any) c.Int, pCtx any) c.Int

//so:extern sqlite3_progress_handler
func Progress_handler(arg0 *Sqlite3, arg1 c.Int, arg2 func(any) c.Int, arg3 any)

//so:extern sqlite3_open
func Open(filename string, ppDb **Sqlite3) c.Int

//so:extern sqlite3_open16
func Open16(filename any, ppDb **Sqlite3) c.Int

//so:extern sqlite3_open_v2
func Open_v2(filename string, ppDb **Sqlite3, flags c.Int, zVfs string) c.Int

//so:extern sqlite3_uri_parameter
func Uri_parameter(z string, zParam string) *c.ConstChar

//so:extern sqlite3_uri_boolean
func Uri_boolean(z string, zParam string, bDefault c.Int) c.Int

//so:extern sqlite3_uri_int64
func Uri_int64(arg0 string, arg1 string, arg2 c.LongLong) c.LongLong

//so:extern sqlite3_uri_key
func Uri_key(z string, N c.Int) *c.ConstChar

//so:extern sqlite3_filename_database
func Filename_database(arg0 string) *c.ConstChar

//so:extern sqlite3_filename_journal
func Filename_journal(arg0 string) *c.ConstChar

//so:extern sqlite3_filename_wal
func Filename_wal(arg0 string) *c.ConstChar

//so:extern sqlite3_database_file_object
func Database_file_object(arg0 string) *File

//so:extern sqlite3_create_filename
func Create_filename(zDatabase string, zJournal string, zWal string, nParam c.Int, azParam **c.ConstChar) *c.ConstChar

//so:extern sqlite3_free_filename
func Free_filename(arg0 string)

//so:extern sqlite3_errcode
func Errcode(db *Sqlite3) c.Int

//so:extern sqlite3_extended_errcode
func Extended_errcode(db *Sqlite3) c.Int

//so:extern sqlite3_errmsg
func Errmsg(arg0 *Sqlite3) *c.ConstChar

//so:extern sqlite3_errmsg16
func Errmsg16(arg0 *Sqlite3) any

//so:extern sqlite3_errstr
func Errstr(arg0 c.Int) *c.ConstChar

//so:extern sqlite3_error_offset
func Error_offset(db *Sqlite3) c.Int

//so:extern sqlite3_set_errmsg
func Set_errmsg(db *Sqlite3, errcode c.Int, zErrMsg string) c.Int

//so:extern sqlite3_limit
func Limit(arg0 *Sqlite3, id c.Int, newVal c.Int) c.Int

//so:extern sqlite3_prepare
func Prepare(db *Sqlite3, zSql string, nByte c.Int, ppStmt **Stmt, pzTail **c.ConstChar) c.Int

//so:extern sqlite3_prepare_v2
func Prepare_v2(db *Sqlite3, zSql string, nByte c.Int, ppStmt **Stmt, pzTail **c.ConstChar) c.Int

//so:extern sqlite3_prepare_v3
func Prepare_v3(db *Sqlite3, zSql string, nByte c.Int, prepFlags c.UInt, ppStmt **Stmt, pzTail **c.ConstChar) c.Int

//so:extern sqlite3_prepare16
func Prepare16(db *Sqlite3, zSql any, nByte c.Int, ppStmt **Stmt, pzTail *any) c.Int

//so:extern sqlite3_prepare16_v2
func Prepare16_v2(db *Sqlite3, zSql any, nByte c.Int, ppStmt **Stmt, pzTail *any) c.Int

//so:extern sqlite3_prepare16_v3
func Prepare16_v3(db *Sqlite3, zSql any, nByte c.Int, prepFlags c.UInt, ppStmt **Stmt, pzTail *any) c.Int

//so:extern sqlite3_sql
func Sql(pStmt *Stmt) *c.ConstChar

//so:extern sqlite3_expanded_sql
func Expanded_sql(pStmt *Stmt) *c.Char

//so:extern sqlite3_stmt_readonly
func Stmt_readonly(pStmt *Stmt) c.Int

//so:extern sqlite3_stmt_isexplain
func Stmt_isexplain(pStmt *Stmt) c.Int

//so:extern sqlite3_stmt_explain
func Stmt_explain(pStmt *Stmt, eMode c.Int) c.Int

//so:extern sqlite3_stmt_busy
func Stmt_busy(arg0 *Stmt) c.Int

//so:extern sqlite3_bind_blob
func Bind_blob(arg0 *Stmt, arg1 c.Int, arg2 any, n c.Int, arg4 func(any)) c.Int

//so:extern sqlite3_bind_blob64
func Bind_blob64(arg0 *Stmt, arg1 c.Int, arg2 any, arg3 c.ULongLong, arg4 func(any)) c.Int

//so:extern sqlite3_bind_double
func Bind_double(arg0 *Stmt, arg1 c.Int, arg2 float64) c.Int

//so:extern sqlite3_bind_int
func Bind_int(arg0 *Stmt, arg1 c.Int, arg2 c.Int) c.Int

//so:extern sqlite3_bind_int64
func Bind_int64(arg0 *Stmt, arg1 c.Int, arg2 c.LongLong) c.Int

//so:extern sqlite3_bind_null
func Bind_null(arg0 *Stmt, arg1 c.Int) c.Int

//so:extern sqlite3_bind_text
func Bind_text(arg0 *Stmt, arg1 c.Int, arg2 string, arg3 c.Int, arg4 func(any)) c.Int

//so:extern sqlite3_bind_text16
func Bind_text16(arg0 *Stmt, arg1 c.Int, arg2 any, arg3 c.Int, arg4 func(any)) c.Int

//so:extern sqlite3_bind_text64
func Bind_text64(arg0 *Stmt, arg1 c.Int, arg2 string, arg3 c.ULongLong, arg4 func(any), encoding c.UChar) c.Int

//so:extern sqlite3_bind_value
func Bind_value(arg0 *Stmt, arg1 c.Int, arg2 *Value) c.Int

//so:extern sqlite3_bind_pointer
func Bind_pointer(arg0 *Stmt, arg1 c.Int, arg2 any, arg3 string, arg4 func(any)) c.Int

//so:extern sqlite3_bind_zeroblob
func Bind_zeroblob(arg0 *Stmt, arg1 c.Int, n c.Int) c.Int

//so:extern sqlite3_bind_zeroblob64
func Bind_zeroblob64(arg0 *Stmt, arg1 c.Int, arg2 c.ULongLong) c.Int

//so:extern sqlite3_bind_parameter_count
func Bind_parameter_count(arg0 *Stmt) c.Int

//so:extern sqlite3_bind_parameter_name
func Bind_parameter_name(arg0 *Stmt, arg1 c.Int) *c.ConstChar

//so:extern sqlite3_bind_parameter_index
func Bind_parameter_index(arg0 *Stmt, zName string) c.Int

//so:extern sqlite3_clear_bindings
func Clear_bindings(arg0 *Stmt) c.Int

//so:extern sqlite3_column_count
func Column_count(pStmt *Stmt) c.Int

//so:extern sqlite3_column_name
func Column_name(arg0 *Stmt, N c.Int) *c.ConstChar

//so:extern sqlite3_column_name16
func Column_name16(arg0 *Stmt, N c.Int) any

//so:extern sqlite3_column_database_name
func Column_database_name(arg0 *Stmt, arg1 c.Int) *c.ConstChar

//so:extern sqlite3_column_database_name16
func Column_database_name16(arg0 *Stmt, arg1 c.Int) any

//so:extern sqlite3_column_table_name
func Column_table_name(arg0 *Stmt, arg1 c.Int) *c.ConstChar

//so:extern sqlite3_column_table_name16
func Column_table_name16(arg0 *Stmt, arg1 c.Int) any

//so:extern sqlite3_column_origin_name
func Column_origin_name(arg0 *Stmt, arg1 c.Int) *c.ConstChar

//so:extern sqlite3_column_origin_name16
func Column_origin_name16(arg0 *Stmt, arg1 c.Int) any

//so:extern sqlite3_column_decltype
func Column_decltype(arg0 *Stmt, arg1 c.Int) *c.ConstChar

//so:extern sqlite3_column_decltype16
func Column_decltype16(arg0 *Stmt, arg1 c.Int) any

//so:extern sqlite3_step
func Step(arg0 *Stmt) c.Int

//so:extern sqlite3_data_count
func Data_count(pStmt *Stmt) c.Int

//so:extern sqlite3_column_blob
func Column_blob(arg0 *Stmt, iCol c.Int) any

//so:extern sqlite3_column_double
func Column_double(arg0 *Stmt, iCol c.Int) float64

//so:extern sqlite3_column_int
func Column_int(arg0 *Stmt, iCol c.Int) c.Int

//so:extern sqlite3_column_int64
func Column_int64(arg0 *Stmt, iCol c.Int) c.LongLong

//so:extern sqlite3_column_text
func Column_text(arg0 *Stmt, iCol c.Int) *c.UChar

//so:extern sqlite3_column_text16
func Column_text16(arg0 *Stmt, iCol c.Int) any

//so:extern sqlite3_column_value
func Column_value(arg0 *Stmt, iCol c.Int) *Value

//so:extern sqlite3_column_bytes
func Column_bytes(arg0 *Stmt, iCol c.Int) c.Int

//so:extern sqlite3_column_bytes16
func Column_bytes16(arg0 *Stmt, iCol c.Int) c.Int

//so:extern sqlite3_column_type
func Column_type(arg0 *Stmt, iCol c.Int) c.Int

//so:extern sqlite3_finalize
func Finalize(pStmt *Stmt) c.Int

//so:extern sqlite3_reset
func Reset(pStmt *Stmt) c.Int

//so:extern sqlite3_create_function
func Create_function(db *Sqlite3, zFunctionName string, nArg c.Int, eTextRep c.Int, pApp any, xFunc func(*Context, c.Int, **Value), xStep func(*Context, c.Int, **Value), xFinal func(*Context)) c.Int

//so:extern sqlite3_create_function16
func Create_function16(db *Sqlite3, zFunctionName any, nArg c.Int, eTextRep c.Int, pApp any, xFunc func(*Context, c.Int, **Value), xStep func(*Context, c.Int, **Value), xFinal func(*Context)) c.Int

//so:extern sqlite3_create_function_v2
func Create_function_v2(db *Sqlite3, zFunctionName string, nArg c.Int, eTextRep c.Int, pApp any, xFunc func(*Context, c.Int, **Value), xStep func(*Context, c.Int, **Value), xFinal func(*Context), xDestroy func(any)) c.Int

//so:extern sqlite3_create_window_function
func Create_window_function(db *Sqlite3, zFunctionName string, nArg c.Int, eTextRep c.Int, pApp any, xStep func(*Context, c.Int, **Value), xFinal func(*Context), xValue func(*Context), xInverse func(*Context, c.Int, **Value), xDestroy func(any)) c.Int

//so:extern sqlite3_aggregate_count
func Aggregate_count(arg0 *Context) c.Int

//so:extern sqlite3_expired
func Expired(arg0 *Stmt) c.Int

//so:extern sqlite3_transfer_bindings
func Transfer_bindings(arg0 *Stmt, arg1 *Stmt) c.Int

//so:extern sqlite3_global_recover
func Global_recover() c.Int

//so:extern sqlite3_thread_cleanup
func Thread_cleanup()

//so:extern sqlite3_memory_alarm
func Memory_alarm(arg0 func(any, c.LongLong, c.Int), arg1 any, arg2 c.LongLong) c.Int

//so:extern sqlite3_value_blob
func Value_blob(arg0 *Value) any

//so:extern sqlite3_value_double
func Value_double(arg0 *Value) float64

//so:extern sqlite3_value_int
func Value_int(arg0 *Value) c.Int

//so:extern sqlite3_value_int64
func Value_int64(arg0 *Value) c.LongLong

//so:extern sqlite3_value_pointer
func Value_pointer(arg0 *Value, arg1 string) any

//so:extern sqlite3_value_text
func Value_text(arg0 *Value) *c.UChar

//so:extern sqlite3_value_text16
func Value_text16(arg0 *Value) any

//so:extern sqlite3_value_text16le
func Value_text16le(arg0 *Value) any

//so:extern sqlite3_value_text16be
func Value_text16be(arg0 *Value) any

//so:extern sqlite3_value_bytes
func Value_bytes(arg0 *Value) c.Int

//so:extern sqlite3_value_bytes16
func Value_bytes16(arg0 *Value) c.Int

//so:extern sqlite3_value_type
func Value_type(arg0 *Value) c.Int

//so:extern sqlite3_value_numeric_type
func Value_numeric_type(arg0 *Value) c.Int

//so:extern sqlite3_value_nochange
func Value_nochange(arg0 *Value) c.Int

//so:extern sqlite3_value_frombind
func Value_frombind(arg0 *Value) c.Int

//so:extern sqlite3_value_encoding
func Value_encoding(arg0 *Value) c.Int

//so:extern sqlite3_value_subtype
func Value_subtype(arg0 *Value) c.UInt

//so:extern sqlite3_value_dup
func Value_dup(arg0 *Value) *Value

//so:extern sqlite3_value_free
func Value_free(arg0 *Value)

//so:extern sqlite3_aggregate_context
func Aggregate_context(arg0 *Context, nBytes c.Int) any

//so:extern sqlite3_user_data
func User_data(arg0 *Context) any

//so:extern sqlite3_context_db_handle
func Context_db_handle(arg0 *Context) *Sqlite3

//so:extern sqlite3_get_auxdata
func Get_auxdata(arg0 *Context, N c.Int) any

//so:extern sqlite3_set_auxdata
func Set_auxdata(arg0 *Context, N c.Int, arg2 any, arg3 func(any))

//so:extern sqlite3_get_clientdata
func Get_clientdata(arg0 *Sqlite3, arg1 string) any

//so:extern sqlite3_set_clientdata
func Set_clientdata(arg0 *Sqlite3, arg1 string, arg2 any, arg3 func(any)) c.Int

//so:extern sqlite3_result_blob
func Result_blob(arg0 *Context, arg1 any, arg2 c.Int, arg3 func(any))

//so:extern sqlite3_result_blob64
func Result_blob64(arg0 *Context, arg1 any, arg2 c.ULongLong, arg3 func(any))

//so:extern sqlite3_result_double
func Result_double(arg0 *Context, arg1 float64)

//so:extern sqlite3_result_error
func Result_error(arg0 *Context, arg1 string, arg2 c.Int)

//so:extern sqlite3_result_error16
func Result_error16(arg0 *Context, arg1 any, arg2 c.Int)

//so:extern sqlite3_result_error_toobig
func Result_error_toobig(arg0 *Context)

//so:extern sqlite3_result_error_nomem
func Result_error_nomem(arg0 *Context)

//so:extern sqlite3_result_error_code
func Result_error_code(arg0 *Context, arg1 c.Int)

//so:extern sqlite3_result_int
func Result_int(arg0 *Context, arg1 c.Int)

//so:extern sqlite3_result_int64
func Result_int64(arg0 *Context, arg1 c.LongLong)

//so:extern sqlite3_result_null
func Result_null(arg0 *Context)

//so:extern sqlite3_result_text
func Result_text(arg0 *Context, arg1 string, arg2 c.Int, arg3 func(any))

//so:extern sqlite3_result_text64
func Result_text64(arg0 *Context, z string, n c.ULongLong, arg3 func(any), encoding c.UChar)

//so:extern sqlite3_result_text16
func Result_text16(arg0 *Context, arg1 any, arg2 c.Int, arg3 func(any))

//so:extern sqlite3_result_text16le
func Result_text16le(arg0 *Context, arg1 any, arg2 c.Int, arg3 func(any))

//so:extern sqlite3_result_text16be
func Result_text16be(arg0 *Context, arg1 any, arg2 c.Int, arg3 func(any))

//so:extern sqlite3_result_value
func Result_value(arg0 *Context, arg1 *Value)

//so:extern sqlite3_result_pointer
func Result_pointer(arg0 *Context, arg1 any, arg2 string, arg3 func(any))

//so:extern sqlite3_result_zeroblob
func Result_zeroblob(arg0 *Context, n c.Int)

//so:extern sqlite3_result_zeroblob64
func Result_zeroblob64(arg0 *Context, n c.ULongLong) c.Int

//so:extern sqlite3_result_subtype
func Result_subtype(arg0 *Context, arg1 c.UInt)

//so:extern sqlite3_create_collation
func Create_collation(arg0 *Sqlite3, zName string, eTextRep c.Int, pArg any, xCompare func(any, c.Int, *c.ConstVoid, c.Int, *c.ConstVoid) c.Int) c.Int

//so:extern sqlite3_create_collation_v2
func Create_collation_v2(arg0 *Sqlite3, zName string, eTextRep c.Int, pArg any, xCompare func(any, c.Int, *c.ConstVoid, c.Int, *c.ConstVoid) c.Int, xDestroy func(any)) c.Int

//so:extern sqlite3_create_collation16
func Create_collation16(arg0 *Sqlite3, zName any, eTextRep c.Int, pArg any, xCompare func(any, c.Int, *c.ConstVoid, c.Int, *c.ConstVoid) c.Int) c.Int

//so:extern sqlite3_collation_needed
func Collation_needed(arg0 *Sqlite3, arg1 any, arg2 func(any, *Sqlite3, c.Int, *c.ConstChar)) c.Int

//so:extern sqlite3_collation_needed16
func Collation_needed16(arg0 *Sqlite3, arg1 any, arg2 func(any, *Sqlite3, c.Int, *c.ConstVoid)) c.Int

//so:extern sqlite3_sleep
func Sleep(arg0 c.Int) c.Int

//so:extern sqlite3_win32_set_directory
func Win32_set_directory(type_ c.ULong, zValue any) c.Int

//so:extern sqlite3_win32_set_directory8
func Win32_set_directory8(type_ c.ULong, zValue string) c.Int

//so:extern sqlite3_win32_set_directory16
func Win32_set_directory16(type_ c.ULong, zValue any) c.Int

//so:extern sqlite3_get_autocommit
func Get_autocommit(arg0 *Sqlite3) c.Int

//so:extern sqlite3_db_handle
func Db_handle(arg0 *Stmt) *Sqlite3

//so:extern sqlite3_db_name
func Db_name(db *Sqlite3, N c.Int) *c.ConstChar

//so:extern sqlite3_db_filename
func Db_filename(db *Sqlite3, zDbName string) *c.ConstChar

//so:extern sqlite3_db_readonly
func Db_readonly(db *Sqlite3, zDbName string) c.Int

//so:extern sqlite3_txn_state
func Txn_state(arg0 *Sqlite3, zSchema string) c.Int

//so:extern sqlite3_next_stmt
func Next_stmt(pDb *Sqlite3, pStmt *Stmt) *Stmt

//so:extern sqlite3_commit_hook
func Commit_hook(arg0 *Sqlite3, arg1 func(any) c.Int, arg2 any) any

//so:extern sqlite3_rollback_hook
func Rollback_hook(arg0 *Sqlite3, arg1 func(any), arg2 any) any

//so:extern sqlite3_autovacuum_pages
func Autovacuum_pages(db *Sqlite3, arg1 func(any, *c.ConstChar, c.UInt, c.UInt, c.UInt) c.UInt, arg2 any, arg3 func(any)) c.Int

//so:extern sqlite3_update_hook
func Update_hook(arg0 *Sqlite3, arg1 func(any, c.Int, *c.ConstChar, *c.ConstChar, c.LongLong), arg2 any) any

//so:extern sqlite3_enable_shared_cache
func Enable_shared_cache(arg0 c.Int) c.Int

//so:extern sqlite3_release_memory
func Release_memory(arg0 c.Int) c.Int

//so:extern sqlite3_db_release_memory
func Db_release_memory(arg0 *Sqlite3) c.Int

//so:extern sqlite3_soft_heap_limit64
func Soft_heap_limit64(N c.LongLong) c.LongLong

//so:extern sqlite3_hard_heap_limit64
func Hard_heap_limit64(N c.LongLong) c.LongLong

//so:extern sqlite3_soft_heap_limit
func Soft_heap_limit(N c.Int)

//so:extern sqlite3_table_column_metadata
func Table_column_metadata(db *Sqlite3, zDbName string, zTableName string, zColumnName string, pzDataType **c.ConstChar, pzCollSeq **c.ConstChar, pNotNull *c.Int, pPrimaryKey *c.Int, pAutoinc *c.Int) c.Int

//so:extern sqlite3_load_extension
func Load_extension(db *Sqlite3, zFile string, zProc string, pzErrMsg **c.Char) c.Int

//so:extern sqlite3_enable_load_extension
func Enable_load_extension(db *Sqlite3, onoff c.Int) c.Int

//so:extern sqlite3_auto_extension
func Auto_extension(xEntryPoint func()) c.Int

//so:extern sqlite3_cancel_auto_extension
func Cancel_auto_extension(xEntryPoint func()) c.Int

//so:extern sqlite3_reset_auto_extension
func Reset_auto_extension()

//so:extern sqlite3_create_module
func Create_module(db *Sqlite3, zName string, p *Module, pClientData any) c.Int

//so:extern sqlite3_create_module_v2
func Create_module_v2(db *Sqlite3, zName string, p *Module, pClientData any, xDestroy func(any)) c.Int

//so:extern sqlite3_drop_modules
func Drop_modules(db *Sqlite3, azKeep **c.ConstChar) c.Int

//so:extern sqlite3_declare_vtab
func Declare_vtab(arg0 *Sqlite3, zSQL string) c.Int

//so:extern sqlite3_overload_function
func Overload_function(arg0 *Sqlite3, zFuncName string, nArg c.Int) c.Int

//so:extern sqlite3_blob_open
func Blob_open(arg0 *Sqlite3, zDb string, zTable string, zColumn string, iRow c.LongLong, flags c.Int, ppBlob **Blob) c.Int

//so:extern sqlite3_blob_reopen
func Blob_reopen(arg0 *Blob, arg1 c.LongLong) c.Int

//so:extern sqlite3_blob_close
func Blob_close(arg0 *Blob) c.Int

//so:extern sqlite3_blob_bytes
func Blob_bytes(arg0 *Blob) c.Int

//so:extern sqlite3_blob_read
func Blob_read(arg0 *Blob, Z any, N c.Int, iOffset c.Int) c.Int

//so:extern sqlite3_blob_write
func Blob_write(arg0 *Blob, z any, n c.Int, iOffset c.Int) c.Int

//so:extern sqlite3_vfs_find
func Vfs_find(zVfsName string) *Vfs

//so:extern sqlite3_vfs_register
func Vfs_register(arg0 *Vfs, makeDflt c.Int) c.Int

//so:extern sqlite3_vfs_unregister
func Vfs_unregister(arg0 *Vfs) c.Int

//so:extern sqlite3_mutex_alloc
func Mutex_alloc(arg0 c.Int) *Mutex

//so:extern sqlite3_mutex_free
func Mutex_free(arg0 *Mutex)

//so:extern sqlite3_mutex_enter
func Mutex_enter(arg0 *Mutex)

//so:extern sqlite3_mutex_try
func Mutex_try(arg0 *Mutex) c.Int

//so:extern sqlite3_mutex_leave
func Mutex_leave(arg0 *Mutex)

//so:extern sqlite3_mutex_held
func Mutex_held(arg0 *Mutex) c.Int

//so:extern sqlite3_mutex_notheld
func Mutex_notheld(arg0 *Mutex) c.Int

//so:extern sqlite3_db_mutex
func Db_mutex(arg0 *Sqlite3) *Mutex

//so:extern sqlite3_file_control
func File_control(arg0 *Sqlite3, zDbName string, op c.Int, arg3 any) c.Int

//so:extern sqlite3_test_control
func Test_control(op c.Int, args ...any) c.Int

//so:extern sqlite3_keyword_count
func Keyword_count() c.Int

//so:extern sqlite3_keyword_name
func Keyword_name(arg0 c.Int, arg1 **c.ConstChar, arg2 *c.Int) c.Int

//so:extern sqlite3_keyword_check
func Keyword_check(arg0 string, arg1 c.Int) c.Int

//so:extern sqlite3_str_new
func Str_new(arg0 *Sqlite3) *Str

//so:extern sqlite3_str_finish
func Str_finish(arg0 *Str) *c.Char

//so:extern sqlite3_str_free
func Str_free(arg0 *Str)

//so:extern sqlite3_str_appendf
func Str_appendf(arg0 *Str, zFormat string, args ...any)

//so:extern sqlite3_str_vappendf
func Str_vappendf(arg0 *Str, zFormat string, arg2 any)

//so:extern sqlite3_str_append
func Str_append(arg0 *Str, zIn string, N c.Int)

//so:extern sqlite3_str_appendall
func Str_appendall(arg0 *Str, zIn string)

//so:extern sqlite3_str_appendchar
func Str_appendchar(arg0 *Str, N c.Int, C c.Char)

//so:extern sqlite3_str_reset
func Str_reset(arg0 *Str)

//so:extern sqlite3_str_truncate
func Str_truncate(arg0 *Str, N c.Int)

//so:extern sqlite3_str_errcode
func Str_errcode(arg0 *Str) c.Int

//so:extern sqlite3_str_length
func Str_length(arg0 *Str) c.Int

//so:extern sqlite3_str_value
func Str_value(arg0 *Str) *c.Char

//so:extern sqlite3_status
func Status(op c.Int, pCurrent *c.Int, pHighwater *c.Int, resetFlag c.Int) c.Int

//so:extern sqlite3_status64
func Status64(op c.Int, pCurrent *c.LongLong, pHighwater *c.LongLong, resetFlag c.Int) c.Int

//so:extern sqlite3_db_status
func Db_status(arg0 *Sqlite3, op c.Int, pCur *c.Int, pHiwtr *c.Int, resetFlg c.Int) c.Int

//so:extern sqlite3_db_status64
func Db_status64(arg0 *Sqlite3, arg1 c.Int, arg2 *c.LongLong, arg3 *c.LongLong, arg4 c.Int) c.Int

//so:extern sqlite3_stmt_status
func Stmt_status(arg0 *Stmt, op c.Int, resetFlg c.Int) c.Int

//so:extern sqlite3_backup_init
func Backup_init(pDest *Sqlite3, zDestName string, pSource *Sqlite3, zSourceName string) *Backup

//so:extern sqlite3_backup_step
func Backup_step(p *Backup, nPage c.Int) c.Int

//so:extern sqlite3_backup_finish
func Backup_finish(p *Backup) c.Int

//so:extern sqlite3_backup_remaining
func Backup_remaining(p *Backup) c.Int

//so:extern sqlite3_backup_pagecount
func Backup_pagecount(p *Backup) c.Int

//so:extern sqlite3_unlock_notify
func Unlock_notify(pBlocked *Sqlite3, xNotify func(*any, c.Int), pNotifyArg any) c.Int

//so:extern sqlite3_stricmp
func Stricmp(arg0 string, arg1 string) c.Int

//so:extern sqlite3_strnicmp
func Strnicmp(arg0 string, arg1 string, arg2 c.Int) c.Int

//so:extern sqlite3_strglob
func Strglob(zGlob string, zStr string) c.Int

//so:extern sqlite3_strlike
func Strlike(zGlob string, zStr string, cEsc c.UInt) c.Int

//so:extern sqlite3_log
func Log(iErrCode c.Int, zFormat string, args ...any)

//so:extern sqlite3_wal_hook
func Wal_hook(arg0 *Sqlite3, arg1 func(any, *Sqlite3, *c.ConstChar, c.Int) c.Int, arg2 any) any

//so:extern sqlite3_wal_autocheckpoint
func Wal_autocheckpoint(db *Sqlite3, N c.Int) c.Int

//so:extern sqlite3_wal_checkpoint
func Wal_checkpoint(db *Sqlite3, zDb string) c.Int

//so:extern sqlite3_wal_checkpoint_v2
func Wal_checkpoint_v2(db *Sqlite3, zDb string, eMode c.Int, pnLog *c.Int, pnCkpt *c.Int) c.Int

//so:extern sqlite3_vtab_config
func Vtab_config(arg0 *Sqlite3, op c.Int, args ...any) c.Int

//so:extern sqlite3_vtab_on_conflict
func Vtab_on_conflict(arg0 *Sqlite3) c.Int

//so:extern sqlite3_vtab_nochange
func Vtab_nochange(arg0 *Context) c.Int

//so:extern sqlite3_vtab_collation
func Vtab_collation(arg0 *Index_info, arg1 c.Int) *c.ConstChar

//so:extern sqlite3_vtab_distinct
func Vtab_distinct(arg0 *Index_info) c.Int

//so:extern sqlite3_vtab_in
func Vtab_in(arg0 *Index_info, iCons c.Int, bHandle c.Int) c.Int

//so:extern sqlite3_vtab_in_first
func Vtab_in_first(pVal *Value, ppOut **Value) c.Int

//so:extern sqlite3_vtab_in_next
func Vtab_in_next(pVal *Value, ppOut **Value) c.Int

//so:extern sqlite3_vtab_rhs_value
func Vtab_rhs_value(arg0 *Index_info, arg1 c.Int, ppVal **Value) c.Int

//so:extern sqlite3_stmt_scanstatus
func Stmt_scanstatus(pStmt *Stmt, idx c.Int, iScanStatusOp c.Int, pOut any) c.Int

//so:extern sqlite3_stmt_scanstatus_v2
func Stmt_scanstatus_v2(pStmt *Stmt, idx c.Int, iScanStatusOp c.Int, flags c.Int, pOut any) c.Int

//so:extern sqlite3_stmt_scanstatus_reset
func Stmt_scanstatus_reset(arg0 *Stmt)

//so:extern sqlite3_db_cacheflush
func Db_cacheflush(arg0 *Sqlite3) c.Int

//so:extern sqlite3_system_errno
func System_errno(arg0 *Sqlite3) c.Int

//so:extern sqlite3_snapshot_get
func Snapshot_get(db *Sqlite3, zSchema string, ppSnapshot **Snapshot) c.Int

//so:extern sqlite3_snapshot_open
func Snapshot_open(db *Sqlite3, zSchema string, pSnapshot *Snapshot) c.Int

//so:extern sqlite3_snapshot_free
func Snapshot_free(arg0 *Snapshot)

//so:extern sqlite3_snapshot_cmp
func Snapshot_cmp(p1 *Snapshot, p2 *Snapshot) c.Int

//so:extern sqlite3_snapshot_recover
func Snapshot_recover(db *Sqlite3, zDb string) c.Int

//so:extern sqlite3_serialize
func Serialize(db *Sqlite3, zSchema string, piSize *c.LongLong, mFlags c.UInt) *c.UChar

//so:extern sqlite3_deserialize
func Deserialize(db *Sqlite3, zSchema string, pData *c.UChar, szDb c.LongLong, szBuf c.LongLong, mFlags c.UInt) c.Int

//so:extern sqlite3_carray_bind_v2
func Carray_bind_v2(pStmt *Stmt, i c.Int, aData any, nData c.Int, mFlags c.Int, xDel func(any), pDel any) c.Int

//so:extern sqlite3_carray_bind
func Carray_bind(pStmt *Stmt, i c.Int, aData any, nData c.Int, mFlags c.Int, xDel func(any)) c.Int

//so:extern sqlite3_rtree_geometry_callback
func Rtree_geometry_callback(db *Sqlite3, zGeom string, xGeom func(*Rtree_geometry, c.Int, *float64, *c.Int) c.Int, pContext any) c.Int

//so:extern sqlite3_rtree_query_callback
func Rtree_query_callback(db *Sqlite3, zQueryFunc string, xQueryFunc func(*Rtree_query_info) c.Int, pContext any, xDestructor func(any)) c.Int
